flowchart LR
  n0["结局-体力耗尽"]
  n1["直面尸潮"]
  n2["结局-尸潮撕碎了你"]
  n3["整理整理"]
  n4["整理整理-看时间"]
  n5["整理整理-王知筠手机"]
  n6["整理整理-王知筠手机-充电"]
  n7["整理整理-王知筠手机-视频"]
  n8["整理整理-喝水"]
  n9["整理整理-脱无尘服"]
  n10["整理整理-吃冻肉"]
  n11["整理整理-吃饼干"]
  n12["整理整理-吃炒米"]
  n13["整理整理-吃磨牙饼干"]
  n14["整理整理-吃食堂干粮"]
  n15["整理整理-吃小饼干"]
  n16["整理整理-吃夹心饼干"]
  n17["整理整理-吃火腿肠"]
  n18["整理整理-吃泡面"]
  n19["整理整理-吃罐头"]
  n20["整理整理-吃维C"]
  n21["整理整理-碘伏消毒"]
  n22["整理整理-吃假解毒剂"]
  n23["整理整理-服药丸"]
  n24["整理整理-退烧"]
  n25["整理整理-导航"]
  n26["整理整理-导航-结果"]
  n27["整理整理-导航-查无"]
  n28["start"]
  n29["结局-汞中毒尸变"]
  n30["↔{positionAfter…"]:::ext
  n31["↔长者食堂-手机信息"]:::ext
  n32["↔初始卧室"]:::ext
  n3 --> n3
  n3 --> n8
  n3 --> n9
  n3 --> n10
  n3 --> n11
  n3 --> n18
  n3 --> n19
  n3 --> n22
  n3 --> n15
  n3 --> n17
  n3 --> n12
  n3 --> n16
  n3 --> n13
  n3 --> n14
  n3 --> n20
  n3 --> n23
  n3 --> n21
  n3 --> n24
  n3 --> n4
  n3 --> n5
  n3 --> n25
  n4 --> n3
  n5 --> n7
  n5 --> n6
  n5 --> n3
  n6 --> n7
  n6 --> n3
  n7 --> n3
  n8 --> n3
  n9 --> n3
  n10 --> n3
  n11 --> n3
  n12 --> n3
  n13 --> n3
  n14 --> n3
  n15 --> n3
  n16 --> n3
  n17 --> n3
  n18 --> n3
  n19 --> n3
  n20 --> n3
  n21 --> n3
  n22 --> n3
  n23 --> n3
  n24 --> n3
  n25 --> n27
  n25 --> n3
  n26 --> n25
  n26 --> n3
  n27 --> n25
  n27 --> n3
  classDef ext fill:#555,color:#ccc;
