flowchart LR
  n0["警察局"]
  n1["警察局-武器-斧头"]
  n2["警察局-武器-手枪"]
  n3["警察局-武器-匕首"]
  n4["警察局-装备-防毒面具"]
  n5["警察局-北段-无图路口"]
  n6["警察局-北段-持图穿行"]
  n7["警察局-北段-持图失败"]
  n8["↔整理整理"]:::ext
  n9["↔上实南校门口"]:::ext
  n0 --> n1
  n0 --> n2
  n0 --> n3
  n0 --> n4
  n1 --> n0
  n2 --> n0
  n3 --> n0
  n4 --> n0
  n6 --> n0
  n6 -.-> n7
  classDef ext fill:#555,color:#ccc;
