flowchart LR
  n0["长者食堂"]
  n1["结局-闭目养神"]
  n2["长者食堂-休息"]
  n3["长者食堂-关门"]
  n4["长者食堂-打门口丧尸"]
  n5["长者食堂-内部"]
  n6["长者食堂-打饭区"]
  n7["长者食堂-吃饭"]
  n8["长者食堂-后厨"]
  n9["长者食堂-饮水机"]
  n10["长者食堂-饮水机-接水"]
  n11["长者食堂-窗口"]
  n12["长者食堂-窗口-喝汤"]
  n13["长者食堂-办公室"]
  n14["长者食堂-打开路由器"]
  n15["长者食堂-签到机"]
  n16["长者食堂-手机信息"]
  n17["↔三林路-东明路 十字路口"]:::ext
  n18["↔结局-被丧尸扑倒咬死"]:::ext
  n19["↔整理整理"]:::ext
  n20["↔菜市场-员工通道"]:::ext
  n21["↔{positionAfter…"]:::ext
  n0 --> n3
  n0 --> n1
  n0 -.-> n2
  n0 --> n15
  n2 --> n2
  n2 --> n5
  n3 --> n4
  n3 --> n5
  n5 --> n11
  n5 --> n6
  n5 --> n9
  n5 --> n13
  n5 --> n4
  n5 --> n2
  n6 --> n7
  n6 --> n5
  n7 --> n5
  n8 --> n5
  n9 --> n10
  n9 --> n5
  n10 --> n9
  n11 --> n12
  n11 --> n5
  n11 --> n8
  n12 --> n5
  n13 --> n14
  n13 --> n5
  n14 --> n13
  n15 --> n0
  classDef ext fill:#555,color:#ccc;
