flowchart LR
  n0["三林路-路霸-堵路"]
  n1["三林路-路霸-给食物"]
  n2["三林路-路霸-击毙"]
  n3["三林路-路霸-搜身"]
  n4["三林路-路霸-买路"]
  n5["三林路-路霸-搏斗"]
  n6["三林路-路霸-打赢"]
  n7["结局-被路霸打死"]
  n8["天台-卖药郎中"]
  n9["天台-卖药郎中-给食物"]
  n10["天台-卖药郎中-成交"]
  n11["新达汇-喷泉广场-高锦睿-路霸"]
  n12["理发店-打听路况"]
  n13["↔三林路-东明路 十字路口"]:::ext
  n14["↔前往金谊广场-2"]:::ext
  n15["↔新达汇-屋顶花园"]:::ext
  n16["↔新达汇-屋顶花园入口"]:::ext
  n17["↔新达汇-喷泉广场"]:::ext
  n18["↔理发店-店内"]:::ext
  n0 --> n5
  n0 --> n1
  n1 --> n0
  n1 --> n4
  n2 --> n3
  n5 --> n6
  n5 -.-> n7
  n5 -.-> n7
  n8 --> n9
  n9 --> n8
  n9 --> n10
  classDef ext fill:#555,color:#ccc;
