flowchart LR
  n0["菜市场-卷帘门"]
  n1["菜市场-大厅"]
  n2["菜市场-大厅-潜行"]
  n3["菜市场-大厅-清场"]
  n4["菜市场-员工通道"]
  n5["菜市场-通道迷路"]
  n6["菜市场-冷库区"]
  n7["菜市场-冷库区-闭门羹"]
  n8["菜市场-交易点"]
  n9["菜市场-交易点-没东西"]
  n10["菜市场-交易-冻肉"]
  n11["菜市场-交易-水"]
  n12["菜市场-交易-铁棍"]
  n13["菜市场-交易-柴油"]
  n14["菜市场-方姐尸变"]
  n15["↔安盛街西侧"]:::ext
  n16["↔长者食堂-后厨"]:::ext
  n17["↔整理整理"]:::ext
  n0 --> n1
  n1 --> n2
  n1 --> n3
  n1 --> n6
  n2 --> n6
  n2 --> n3
  n3 --> n6
  n4 --> n5
  n4 --> n6
  n5 --> n4
  n6 --> n7
  n6 --> n1
  n6 --> n4
  n7 --> n1
  n7 --> n4
  n8 --> n9
  n8 --> n6
  n8 --> n10
  n8 --> n11
  n8 --> n12
  n9 --> n6
  n10 --> n8
  n10 --> n6
  n11 --> n8
  n11 --> n6
  n12 --> n8
  n12 --> n6
  n13 --> n6
  classDef ext fill:#555,color:#ccc;
