flowchart LR
  n0["小区东门-整装待发"]
  n1["小区西门-整装待发"]
  n2["三林路-环林东路 十字路口"]
  n3["三林路"]
  n4["三林路-北侧"]
  n5["三林路-南侧"]
  n6["三林路-东明路 十字路口"]
  n7["前往金谊广场-1"]
  n8["前往金谊广场-2"]
  n9["三林路-获得一辆轿车"]
  n10["三林路-轿车门锁了"]
  n11["东明路-三林路"]
  n12["结局-丧尸的围殴"]
  n13["银行门口"]
  n14["银行内部"]
  n15["银行-保安室"]
  n16["银行-保安室-歇脚"]
  n17["银行-拿水"]
  n18["银行-金库"]
  n19["银行-存款凭条"]
  n20["联华超市"]
  n21["小超市-香肠"]
  n22["联华超市-吃香肠"]
  n23["联华超市-补给"]
  n24["联华超市-歇脚"]
  n25["联华超市-仓库-遇见周师傅"]
  n26["联华超市-仓库"]
  n27["联华超市-仓库-拿罐头"]
  n28["联华超市-仓库-拿水"]
  n29["小区东门-整装待发-躲藏"]
  n30["三林路-环林东路十字路口-躲藏"]
  n31["三林路-躲藏"]
  n32["三林路-东明路十字路口-躲藏"]
  n33["东明路-三林路-躲藏"]
  n34["↔全家便利店（环林东路）"]:::ext
  n35["↔公交车站（环林东路）"]:::ext
  n36["↔{_sprintDest}"]:::ext
  n37["↔杨高南路立交桥"]:::ext
  n38["↔安盛街东侧"]:::ext
  n39["↔安居苑前门"]:::ext
  n40["↔益丰大药房"]:::ext
  n41["↔五金店"]:::ext
  n42["↔三林路-路霸-堵路"]:::ext
  n43["↔安盛街西侧"]:::ext
  n44["↔长者食堂"]:::ext
  n45["↔金谊广场-龙头区"]:::ext
  n46["↔图书馆"]:::ext
  n47["↔上实南校门口"]:::ext
  n48["↔11号线-三林东路站"]:::ext
  n49["↔整理整理"]:::ext
  n50["↔联华超市-地下室-撬锁"]:::ext
  n51["↔联华超市-地下室-破锁"]:::ext
  n0 --> n29
  n1 --> n11
  n2 --> n3
  n2 --> n30
  n2 -.-> n12
  n3 --> n4
  n3 --> n5
  n3 --> n31
  n3 --> n2
  n3 --> n6
  n3 -.-> n12
  n4 --> n13
  n4 --> n9
  n4 -.-> n10
  n4 --> n20
  n4 --> n5
  n4 --> n3
  n5 --> n4
  n5 --> n3
  n6 --> n11
  n6 --> n3
  n6 --> n32
  n6 -.-> n12
  n7 -.-> n8
  n9 --> n3
  n10 --> n3
  n11 --> n6
  n11 --> n33
  n11 -.-> n12
  n13 --> n14
  n13 --> n3
  n14 --> n15
  n14 --> n19
  n14 --> n3
  n15 --> n17
  n15 --> n16
  n15 --> n18
  n15 --> n14
  n16 --> n16
  n16 --> n14
  n17 --> n14
  n18 --> n14
  n19 --> n14
  n20 --> n23
  n20 --> n26
  n20 --> n24
  n20 --> n3
  n21 --> n22
  n21 --> n20
  n22 --> n20
  n23 --> n20
  n23 --> n21
  n24 --> n24
  n24 --> n20
  n25 --> n26
  n26 --> n28
  n26 --> n27
  n26 --> n20
  n26 --> n26
  n27 --> n26
  n28 --> n26
  n29 --> n29
  n30 --> n30
  n31 --> n31
  n32 --> n32
  n33 --> n33
  classDef ext fill:#555,color:#ccc;
