flowchart LR
  n0["上实南校门口"]
  n1["上实南校-1号楼走廊"]
  n2["上实南校-1号楼走廊-捡书包"]
  n3["上实南校-教务室-翻桌"]
  n4["上实南校-教务室-开柜"]
  n5["上实南校-天桥"]
  n6["上实南校-天桥-润滑油"]
  n7["上实南校-天桥-硬砸"]
  n8["上实南校-2号楼走廊"]
  n9["结局-上实南校-第一次-战斗"]
  n10["结局-上实南校-第一次-跑"]
  n11["上实南校-第一次-躲教室"]
  n12["结局-上实南校-第一次-回马枪"]
  n13["上实南校-3号楼走廊"]
  n14["上实南校-3号楼-2楼"]
  n15["上实南校-3号楼-3楼"]
  n16["上实南校-3号楼-4楼"]
  n17["上实南校-3号楼-4楼-摸黑"]
  n18["上实南校-化学实验室"]
  n19["结局-上实南校-化学实验室-面具坏了被毒死"]
  n20["上实南校-化学实验室-面具有"]
  n21["上实南校-化学实验室-憋气"]
  n22["上实南校-拿到酒精灯"]
  n23["上实南校-拿到盐酸"]
  n24["上实南校-拿到温度计"]
  n25["上实南校-3号楼下楼"]
  n26["上实南校-员工通道-锁着"]
  n27["结局-上实南校-美术室"]
  n28["结局-上实南校-2楼"]
  n29["上实南校-1楼出口"]
  n30["上实南校-员工通道"]
  n31["上实南校-2号楼1楼-二次遭遇"]
  n32["结局-上实南校-二次-无酒精灯"]
  n33["上实南校-二次-桌椅"]
  n34["结局-上实南校-二次-战斗"]
  n35["结局-上实南校-二次-跑"]
  n36["上实南校-酒精灯-投掷"]
  n37["上实南校-酒精灯-再战"]
  n38["结局-上实南校-酒精灯烧死"]
  n39["上实南校-击败体育老师"]
  n40["上实南校-复合楼入口"]
  n41["上实南校-图书馆"]
  n42["上实南校-图书馆-对话"]
  n43["上实南校-图书馆-情报"]
  n44["上实南校-图书馆-给食物-选择"]
  n45["上实南校-图书馆-给食物"]
  n46["上实南校-图书馆-承诺"]
  n47["上实南校-图书馆-给水"]
  n48["上实南校-图书馆-全灭"]
  n49["上实南校-图书馆-给水后"]
  n50["上实南校-体育馆"]
  n51["结局-上实南校-体育馆-战斗"]
  n52["上实南校-食堂"]
  n53["结局-上实南校-食堂-中毒"]
  n54["上实南校-相认"]
  n55["上实南校-相认-说明"]
  n56["上实南校-储备粮"]
  n57["上实南校-储备粮-割开"]
  n58["上实南校-储备粮-撕不开"]
  n59["上实南校-小赵的伤"]
  n60["上实南校-小赵的伤-测温"]
  n61["上实南校-小赵的伤-目测"]
  n62["上实南校-商议撤离"]
  n63["上实南校-翻窗下楼"]
  n64["上实南校-翻窗成功"]
  n65["上实南校-翻窗摔伤"]
  n66["上实南校-翻窗跳下"]
  n67["上实南校-校园后院"]
  n68["上实南校-侧门撤离"]
  n69["上实南校-后门突围"]
  n70["上实南校-后门-盐酸开锁"]
  n71["上实南校-后门-无酸"]
  n72["上实南校-后门-砸锁"]
  n73["上实南校-后门-无工具"]
  n74["上实南校-后门-潜行"]
  n75["上实南校-后门-潜行成功"]
  n76["上实南校-后门-潜行失败"]
  n77["上实南校-原路出校"]
  n78["上实南校-原路-潜行"]
  n79["上实南校-原路-硬冲"]
  n80["上实南校-撤离成功"]
  n81["↔东明路-三林路"]:::ext
  n82["↔警察局-北段-无图路口"]:::ext
  n83["↔警察局-北段-持图穿行"]:::ext
  n0 --> n1
  n1 --> n2
  n1 --> n3
  n1 --> n5
  n1 --> n4
  n2 --> n5
  n3 --> n5
  n4 --> n5
  n5 --> n6
  n5 --> n7
  n5 --> n0
  n6 --> n8
  n7 --> n8
  n8 --> n9
  n8 --> n11
  n8 --> n10
  n8 --> n13
  n8 --> n5
  n11 --> n13
  n11 --> n12
  n13 --> n14
  n13 --> n15
  n13 --> n16
  n13 -.-> n17
  n14 --> n15
  n14 --> n16
  n14 -.-> n17
  n15 --> n14
  n15 --> n27
  n16 --> n18
  n17 --> n18
  n18 --> n20
  n18 -.-> n19
  n18 --> n21
  n20 --> n22
  n20 --> n23
  n20 --> n24
  n21 --> n22
  n22 --> n25
  n23 --> n25
  n24 --> n25
  n25 --> n27
  n25 --> n28
  n25 --> n29
  n25 --> n30
  n25 -.-> n26
  n26 --> n29
  n29 --> n31
  n30 --> n31
  n31 --> n36
  n31 -.-> n32
  n31 --> n33
  n31 --> n34
  n31 --> n35
  n33 --> n36
  n33 -.-> n32
  n33 --> n35
  n36 --> n39
  n36 --> n37
  n36 -.-> n38
  n37 --> n39
  n37 --> n37
  n37 -.-> n38
  n39 --> n40
  n40 --> n54
  n40 --> n50
  n40 --> n52
  n40 --> n41
  n40 --> n80
  n41 --> n42
  n41 --> n40
  n41 --> n48
  n42 --> n43
  n42 --> n44
  n42 --> n47
  n42 --> n40
  n43 --> n46
  n43 --> n40
  n44 --> n42
  n44 --> n45
  n45 --> n46
  n45 --> n40
  n46 --> n40
  n47 --> n40
  n47 --> n49
  n50 --> n40
  n50 --> n51
  n52 --> n53
  n52 --> n40
  n54 --> n55
  n55 --> n56
  n56 --> n57
  n56 -.-> n58
  n56 --> n58
  n57 --> n59
  n58 --> n59
  n59 --> n60
  n59 -.-> n61
  n59 --> n61
  n60 --> n62
  n61 --> n62
  n62 --> n63
  n62 --> n77
  n63 --> n64
  n63 -.-> n65
  n63 --> n66
  n64 --> n67
  n65 --> n67
  n66 --> n67
  n67 --> n68
  n67 --> n69
  n67 --> n77
  n68 --> n80
  n69 --> n70
  n69 -.-> n71
  n69 --> n74
  n69 --> n72
  n69 -.-> n73
  n69 --> n67
  n70 --> n80
  n71 --> n67
  n72 --> n80
  n73 --> n67
  n74 --> n75
  n74 --> n76
  n74 -.-> n76
  n75 --> n80
  n76 --> n80
  n77 --> n78
  n77 --> n79
  n78 --> n80
  n79 --> n80
  classDef ext fill:#555,color:#ccc;
