flowchart LR
  n0["安居苑后门"]
  n1["三林安居苑-驱赶变异猫"]
  n2["三林安居苑-小区内部"]
  n3["三林安居苑-小广场"]
  n4["三林安居苑-小广场-歇脚"]
  n5["三林安居苑-滑板车"]
  n6["三林安居苑-鹅卵石路"]
  n7["三林安居苑-藤蔓丧尸"]
  n8["三林安居苑-割藤蔓"]
  n9["三林安居苑-藤蔓丧尸-战斗"]
  n10["三林安居苑-藤蔓丧尸-击杀"]
  n11["三林安居苑-藤蔓丧尸-被咬"]
  n12["三林安居苑-8号楼-1楼"]
  n13["三林安居苑-8号楼-2楼"]
  n14["三林安居苑-8号楼-203室"]
  n15["三林安居苑-8号楼-203室-书桌"]
  n16["三林安居苑-8号楼-203室-草稿"]
  n17["三林安居苑-8号楼-203室-双肩包"]
  n18["三林安居苑-8号楼-203室-背走双肩包"]
  n19["三林安居苑-8号楼-203室-门禁卡"]
  n20["三林安居苑-8号楼-203室-笔记本"]
  n21["三林安居苑-8号楼-203室-笔记本-开机"]
  n22["三林安居苑-8号楼-203室-笔记本-密码错误"]
  n23["三林安居苑-8号楼-203室-笔记本-桌面"]
  n24["三林安居苑-8号楼-203室-笔记本-B站"]
  n25["三林安居苑-8号楼-203室-笔记本-邮件"]
  n26["三林安居苑-8号楼-204室"]
  n27["三林安居苑-8号楼-204室-老洪"]
  n28["三林安居苑-8号楼-204室-空水瓶"]
  n29["三林安居苑-8号楼-204室-笔记本"]
  n30["三林安居苑-8号楼-204室-防毒面具"]
  n31["三林安居苑-8号楼-204室-翻找"]
  n32["三林安居苑-8号楼-204室-电线"]
  n33["三林安居苑-7号楼-1楼门口"]
  n34["三林安居苑-7号楼-1楼走廊"]
  n35["三林安居苑-7号楼-1楼-某户"]
  n36["三林安居苑-7号楼-2楼"]
  n37["三林安居苑-7号楼-3楼"]
  n38["三林安居苑-7号楼-4楼"]
  n39["三林安居苑-7号楼-6楼"]
  n40["三林安居苑-7号楼-天台破锁"]
  n41["三林安居苑-7号楼-天台"]
  n42["三林安居苑-7号楼-天台-歇脚"]
  n43["三林安居苑-7号楼-5楼"]
  n44["三林安居苑-5楼-门锁了"]
  n45["三林安居苑-502"]
  n46["三林安居苑-502-厨房"]
  n47["三林安居苑-502-客厅"]
  n48["三林安居苑-502-阳台"]
  n49["三林安居苑-502-小卧室"]
  n50["三林安居苑-卧室"]
  n51["三林安居苑-卧室-快速"]
  n52["三林安居苑-卧室-仔细"]
  n53["三林安居苑-厨房"]
  n54["三林安居苑-厨房危险"]
  n55["三林安居苑-自行车"]
  n56["三林安居苑-喜提新车"]
  n57["三林安居苑-骑车失败"]
  n58["安居苑前门"]
  n59["三林安居苑-躲藏"]
  n60["三林安居苑-小区内部-躲藏"]
  n61["三林安居苑-7号楼-201"]
  n62["三林安居苑-7号楼-201-厨房"]
  n63["三林安居苑-7号楼-201-战斗"]
  n64["三林安居苑-7号楼-202"]
  n65["三林安居苑-7号楼-202-厨房"]
  n66["三林安居苑-7号楼-202-战斗"]
  n67["三林安居苑-7号楼-301"]
  n68["三林安居苑-7号楼-301-厨房"]
  n69["三林安居苑-7号楼-301-战斗"]
  n70["三林安居苑-7号楼-302"]
  n71["三林安居苑-7号楼-302-厨房"]
  n72["三林安居苑-7号楼-302-战斗"]
  n73["三林安居苑-7号楼-501"]
  n74["三林安居苑-7号楼-501-厨房"]
  n75["三林安居苑-7号楼-501-战斗"]
  n76["三林安居苑-7号楼-501-砸门"]
  n77["三林安居苑-7号楼-503"]
  n78["三林安居苑-7号楼-503-厨房"]
  n79["三林安居苑-7号楼-503-战斗"]
  n80["三林安居苑-7号楼-503-砸门"]
  n81["三林安居苑-7号楼-401-破门"]
  n82["三林安居苑-7号楼-401"]
  n83["三林安居苑-7号楼-401-补给"]
  n84["结局-安居苑-入户被扑倒"]
  n85["↔安盛街中段"]:::ext
  n86["↔{_sprintDest}"]:::ext
  n87["↔整理整理"]:::ext
  n88["↔三林路"]:::ext
  n0 --> n2
  n0 --> n1
  n0 --> n59
  n1 --> n2
  n2 --> n33
  n2 --> n12
  n2 --> n55
  n2 --> n3
  n2 --> n60
  n3 --> n2
  n3 --> n58
  n3 --> n5
  n3 --> n6
  n3 --> n4
  n3 --> n7
  n4 --> n4
  n4 --> n3
  n5 --> n3
  n6 --> n3
  n7 --> n8
  n7 --> n11
  n7 --> n9
  n7 --> n2
  n8 --> n2
  n9 --> n10
  n9 --> n2
  n10 --> n2
  n11 --> n3
  n12 --> n13
  n12 --> n2
  n13 --> n26
  n13 --> n14
  n13 --> n12
  n14 --> n15
  n14 --> n17
  n14 --> n20
  n14 --> n13
  n15 --> n14
  n15 --> n16
  n16 --> n14
  n17 --> n19
  n17 --> n18
  n17 --> n14
  n18 --> n14
  n19 --> n13
  n20 --> n14
  n20 --> n23
  n20 -.-> n22
  n21 --> n23
  n21 -.-> n22
  n21 --> n20
  n22 --> n23
  n22 -.-> n22
  n22 --> n20
  n23 --> n24
  n23 --> n25
  n23 --> n20
  n24 --> n23
  n25 --> n23
  n26 --> n27
  n26 --> n29
  n26 --> n30
  n26 --> n28
  n26 --> n31
  n26 --> n32
  n26 --> n13
  n27 --> n26
  n28 --> n26
  n29 --> n26
  n30 --> n26
  n31 --> n26
  n32 --> n26
  n33 --> n34
  n33 --> n2
  n34 --> n35
  n34 --> n36
  n34 --> n33
  n35 --> n50
  n35 --> n53
  n35 -.-> n54
  n35 --> n34
  n36 --> n61
  n36 --> n64
  n36 --> n37
  n36 --> n34
  n37 --> n67
  n37 --> n70
  n37 --> n38
  n37 --> n36
  n38 --> n81
  n38 --> n82
  n38 --> n43
  n38 --> n37
  n39 --> n43
  n39 --> n40
  n40 --> n41
  n41 --> n42
  n41 --> n39
  n42 --> n41
  n43 --> n45
  n43 -.-> n44
  n43 --> n73
  n43 --> n76
  n43 --> n77
  n43 --> n80
  n43 --> n39
  n43 --> n38
  n44 --> n38
  n45 --> n46
  n45 --> n47
  n45 --> n48
  n45 --> n49
  n45 --> n43
  n46 --> n45
  n47 --> n45
  n48 --> n45
  n49 --> n45
  n50 --> n51
  n50 --> n52
  n50 --> n35
  n51 --> n35
  n52 --> n52
  n52 --> n35
  n53 --> n35
  n55 --> n56
  n55 -.-> n57
  n55 --> n2
  n56 --> n2
  n57 --> n2
  n58 --> n2
  n59 --> n59
  n60 --> n60
  n61 --> n36
  n62 --> n36
  n63 --> n61
  n64 --> n36
  n65 --> n36
  n66 --> n64
  n67 --> n37
  n68 --> n37
  n69 --> n67
  n70 --> n37
  n71 --> n37
  n72 --> n70
  n73 --> n43
  n74 --> n43
  n75 --> n73
  n76 --> n73
  n77 --> n43
  n78 --> n43
  n79 --> n77
  n80 --> n77
  n81 --> n82
  n82 --> n83
  n82 --> n38
  n83 --> n38
  classDef ext fill:#555,color:#ccc;
