flowchart LR
  n0["益丰大药房"]
  n1["益丰大药房-库房门锁了"]
  n2["益丰大药房-柜台后"]
  n3["结局-益丰-被反杀"]
  n4["益丰大药房-击杀"]
  n5["益丰大药房-柜台后-已清理"]
  n6["利昂药剂师的工牌"]
  n7["益丰大药房-翻找"]
  n8["益丰大药房-库房"]
  n9["益丰大药房-退烧药"]
  n10["益丰大药房-左边货架翻找"]
  n11["益丰大药房-右边货架翻找"]
  n12["益丰大药房-库房里的丧尸"]
  n13["益丰大药房-击倒针筒丧尸"]
  n14["益丰大药房-检查针筒"]
  n15["益丰大药房-办公室门口"]
  n16["益丰大药房-办公室门口-门锁上了"]
  n17["益丰大药房-背后偷袭的丧尸"]
  n18["益丰大药房-沟通被咬"]
  n19["益丰大药房-沟通躲开"]
  n20["益丰大药房-被咬到了"]
  n21["益丰大药房-喂水"]
  n22["益丰大药房-解脱学徒"]
  n23["益丰大药房-学徒的遗物"]
  n24["益丰大药房-解脱后走廊"]
  n25["益丰大药房-解释血迹"]
  n26["益丰大药房-呼叫开门"]
  n27["益丰大药房-推门进入办公室"]
  n28["益丰大药房-办公室闲聊"]
  n29["益丰大药房-办公室闲聊2"]
  n30["益丰大药房-办公室闲聊3"]
  n31["益丰大药房-办公室歇脚"]
  n32["益丰大药房-匀口饭吃"]
  n33["益丰大药房-食物见底"]
  n34["益丰大药房-选择离开的路"]
  n35["益丰大药房-丧尸偷袭，仓皇逃窜"]
  n36["益丰大药房-消防通道"]
  n37["益丰大药房-配电箱"]
  n38["益丰大药房-断电"]
  n39["益丰大药房-打开防火门"]
  n40["益丰大药房-灯光恢复"]
  n41["益丰大药房-与丧尸打群架"]
  n42["↔整理整理"]:::ext
  n43["↔三林路"]:::ext
  n44["↔结局-颜色错误，被丧尸咬死"]:::ext
  n45["↔结局-被丧尸扑倒咬死"]:::ext
  n46["↔三林路-环林东路 十字路口"]:::ext
  n0 --> n2
  n0 --> n5
  n0 --> n7
  n0 --> n8
  n0 -.-> n1
  n0 --> n31
  n1 --> n0
  n2 --> n4
  n2 -.-> n3
  n4 --> n4
  n4 --> n0
  n4 --> n6
  n5 --> n0
  n6 --> n0
  n7 --> n7
  n7 --> n0
  n8 --> n10
  n8 --> n11
  n8 --> n9
  n8 --> n12
  n9 --> n8
  n10 --> n8
  n11 --> n8
  n12 --> n13
  n13 --> n14
  n13 --> n15
  n14 --> n15
  n15 --> n27
  n15 --> n26
  n15 -.-> n16
  n16 --> n17
  n16 --> n26
  n17 --> n18
  n17 --> n15
  n17 --> n22
  n17 --> n36
  n17 --> n24
  n18 --> n19
  n18 -.-> n20
  n19 --> n17
  n20 --> n17
  n21 --> n17
  n22 --> n23
  n22 --> n24
  n23 --> n24
  n24 --> n25
  n25 --> n28
  n26 --> n28
  n27 --> n28
  n28 --> n34
  n28 --> n29
  n29 --> n34
  n29 --> n30
  n30 --> n34
  n31 --> n31
  n31 --> n32
  n31 -.-> n33
  n31 --> n0
  n32 --> n31
  n33 --> n31
  n34 --> n35
  n34 --> n36
  n36 --> n37
  n36 --> n17
  n37 --> n39
  n37 --> n38
  n37 --> n36
  n38 --> n39
  n38 --> n40
  n40 --> n41
  classDef ext fill:#555,color:#ccc;
