flowchart LR
  n0["初始卧室"]
  n1["什么都没有"]
  n2["结局-开幕雷击"]
  n3["玄关"]
  n4["结局-丧尸的凝视"]
  n5["窗外的风景"]
  n6["结局-自尽"]
  n7["床底的食物"]
  n8["闹钟"]
  n9["打开闹钟"]
  n10["客厅"]
  n11["沙发上的小熊"]
  n12["家门外的丧尸"]
  n13["教程-识别颜色躲丧尸"]
  n14["结局-颜色错误，被丧尸咬死"]
  n15["结局-丧尸破门而入"]
  n16["家门外"]
  n17["家外楼梯间的抉择"]
  n18["家门口电梯"]
  n19["结局-电梯门开了"]
  n20["3楼-安全"]
  n21["3楼"]
  n22["结局-来自丧尸的惊吓"]
  n23["结局-反应太慢被咬死了"]
  n24["初遇陈默"]
  n25["结局-被丧尸扑倒咬死"]
  n26["结局-被丧尸扑倒咬死-力竭"]
  n27["结局-1楼-party"]
  n28["B1"]
  n29["B1-2nd"]
  n30["1楼-安全"]
  n31["楼栋告示栏"]
  n32["电梯"]
  n33["小区道路"]
  n34["装睡的丧尸"]
  n35["结局-摇睡丧尸"]
  n36["反杀老6"]
  n37["结局-背后的偷袭-力竭"]
  n38["西出口-丧尸堵路"]
  n39["地下车库的丧尸"]
  n40["结局-嘎吱嘎吱"]
  n41["KO丧尸"]
  n42["陌生的岔路口"]
  n43["地下非机动车停靠区"]
  n44["自行车上锁了"]
  n45["电瓶车上锁了"]
  n46["骑车去西出口"]
  n47["击退丧尸"]
  n48["防爆门"]
  n49["结局-防爆门没锁上"]
  n50["丧尸被防爆门夹扁"]
  n51["西出口"]
  n52["墙上的痕迹"]
  n53["柱子上的纸张"]
  n54["东出口-废车堵路"]
  n55["东出口"]
  n56["没用的按钮"]
  n57["民防设施-等候区"]
  n58["等候区的桌子"]
  n59["抽屉里的手电筒"]
  n60["等候区的扫帚"]
  n61["墙上的民防告示"]
  n62["告示后面的钥匙"]
  n63["民防设施-楼梯间"]
  n64["民防设施-紧急出口"]
  n65["结局-门锁上了"]
  n66["结局-初遇毒气型丧尸"]
  n67["民防设施-物资区"]
  n68["物资区的丧尸"]
  n69["结局-民防设施楼梯断裂"]
  n70["民防设施-通风管道"]
  n71["民防设施-通风管道的抉择"]
  n72["结局-死路一条"]
  n73["拳打脚踢"]
  n74["拳打脚踢2"]
  n75["民防设施-物资区-检修记录表"]
  n76["民防设施-进风机房"]
  n77["日记本的空白页"]
  n78["日记本的提示-打开鼓风机"]
  n79["民防设施-进风机房-安全"]
  n80["民防设施-进风机房-失败"]
  n81["结局-民防设施-绿色亮斑"]
  n82["小区东门"]
  n83["小区西门"]
  n84["樱桃苑-4楼"]
  n85["樱桃苑-4楼-胜利"]
  n86["樱桃苑-4楼-失败"]
  n87["樱桃苑-5楼"]
  n88["樱桃苑-5楼-501"]
  n89["樱桃苑-5楼-501-拿钥匙"]
  n90["樱桃苑-5楼-门锁了"]
  n91["小区草地"]
  n92["小区草地-安全"]
  n93["小区草地-被追"]
  n94["物业楼"]
  n95["物业楼-居委会-门锁了"]
  n96["物业楼-居委会办公室"]
  n97["物业楼-居委会办公室-收起润滑油"]
  n98["物业楼-居委会-给高锦睿"]
  n99["物业楼-高锦睿"]
  n100["物业楼-高锦睿-聊"]
  n101["物业楼-高锦睿-时间"]
  n102["物业楼-高锦睿-无人机"]
  n103["↔整理整理"]:::ext
  n104["↔start"]:::ext
  n105["↔{positionAfter…"]:::ext
  n0 --> n30
  n0 -.-> n2
  n0 --> n0
  n0 --> n5
  n0 --> n8
  n0 --> n7
  n0 -.-> n1
  n1 --> n0
  n3 --> n12
  n3 -.-> n16
  n3 --> n4
  n3 --> n0
  n5 --> n3
  n5 --> n6
  n7 --> n0
  n8 --> n9
  n8 --> n3
  n9 --> n10
  n10 --> n11
  n10 --> n0
  n10 --> n3
  n11 --> n10
  n12 --> n13
  n12 --> n3
  n12 -.-> n25
  n13 --> n17
  n13 -.-> n14
  n13 -.-> n25
  n16 --> n30
  n17 --> n21
  n17 --> n84
  n17 --> n87
  n17 --> n30
  n17 -.-> n27
  n17 --> n28
  n17 --> n18
  n17 -.-> n25
  n18 --> n20
  n18 --> n84
  n18 --> n30
  n18 -.-> n27
  n18 --> n28
  n18 -.-> n19
  n20 --> n17
  n21 --> n22
  n22 --> n22
  n22 -.-> n24
  n22 -.-> n23
  n24 --> n83
  n24 --> n25
  n28 --> n22
  n28 --> n53
  n28 --> n51
  n28 -.-> n38
  n28 --> n55
  n28 -.-> n54
  n28 --> n52
  n29 --> n30
  n29 --> n53
  n29 --> n51
  n29 -.-> n38
  n29 --> n55
  n29 -.-> n54
  n30 --> n33
  n30 --> n31
  n30 --> n32
  n31 --> n30
  n32 --> n16
  n32 --> n20
  n32 --> n84
  n32 --> n28
  n32 --> n30
  n33 --> n34
  n33 --> n91
  n33 --> n83
  n34 --> n35
  n34 --> n36
  n34 -.-> n37
  n36 --> n82
  n36 --> n83
  n38 --> n39
  n38 --> n29
  n38 -.-> n25
  n39 --> n40
  n39 -.-> n26
  n39 --> n41
  n39 --> n47
  n39 -.-> n25
  n41 --> n42
  n42 --> n51
  n42 -.-> n38
  n42 --> n43
  n43 --> n51
  n43 -.-> n38
  n43 --> n44
  n43 --> n46
  n43 -.-> n45
  n43 --> n83
  n44 --> n43
  n45 --> n43
  n46 --> n51
  n47 --> n55
  n47 -.-> n48
  n47 -.-> n25
  n48 --> n49
  n48 --> n50
  n48 -.-> n25
  n50 --> n51
  n50 -.-> n38
  n51 --> n83
  n52 --> n29
  n53 --> n55
  n53 --> n38
  n54 --> n39
  n55 --> n56
  n55 --> n57
  n56 --> n22
  n57 --> n58
  n57 --> n60
  n57 --> n61
  n57 --> n63
  n57 --> n42
  n58 --> n57
  n58 -.-> n15
  n58 --> n59
  n59 --> n57
  n60 --> n57
  n60 -.-> n15
  n61 --> n57
  n61 -.-> n62
  n62 --> n57
  n63 --> n64
  n63 --> n67
  n63 -.-> n25
  n64 --> n25
  n64 --> n65
  n64 --> n66
  n67 --> n68
  n68 --> n25
  n68 --> n73
  n68 --> n70
  n68 --> n57
  n68 -.-> n69
  n68 -.-> n25
  n70 --> n71
  n70 --> n25
  n71 --> n72
  n71 --> n82
  n73 --> n76
  n73 --> n74
  n73 -.-> n25
  n74 --> n79
  n74 --> n75
  n75 --> n79
  n75 --> n57
  n75 -.-> n69
  n76 --> n15
  n76 --> n79
  n76 --> n80
  n76 --> n77
  n77 --> n78
  n77 -.-> n77
  n77 --> n76
  n78 --> n76
  n79 --> n82
  n80 --> n82
  n80 --> n81
  n84 --> n85
  n84 -.-> n86
  n84 -.-> n86
  n85 --> n87
  n85 --> n17
  n86 --> n17
  n87 --> n88
  n87 --> n90
  n87 --> n17
  n88 --> n89
  n88 --> n87
  n89 --> n87
  n90 --> n87
  n91 --> n92
  n91 --> n94
  n91 --> n82
  n91 -.-> n93
  n92 --> n94
  n92 --> n82
  n92 --> n33
  n93 --> n94
  n94 --> n99
  n94 --> n96
  n94 -.-> n95
  n94 --> n82
  n95 --> n94
  n96 --> n98
  n96 --> n97
  n97 --> n94
  n98 --> n99
  n98 --> n92
  n99 --> n100
  n99 --> n102
  n99 --> n101
  n99 --> n82
  n100 --> n102
  n100 --> n101
  n100 --> n82
  n101 --> n99
  n101 --> n82
  n102 --> n99
  n102 --> n92
  classDef ext fill:#555,color:#ccc;
