flowchart LR
  n0["五金店"]
  n1["五金店-正门"]
  n2["五金店-正门-摸黑"]
  n3["结局-五金店-地沟"]
  n4["五金店-正门-照明"]
  n5["结局-五金店-工具区"]
  n6["结局-五金店-迅捷"]
  n7["五金店-前台"]
  n8["结局-五金店-毒气"]
  n9["五金店-侧窗"]
  n10["五金店-侧窗-探索"]
  n11["五金店-货架躲藏"]
  n12["五金店-后巷"]
  n13["五金店-后巷-撬锁"]
  n14["结局-五金店-开门杀"]
  n15["五金店-后巷-偷看左门"]
  n16["结局-配电房"]
  n17["五金店-后巷-偷看右门"]
  n18["结局-五金店-对视"]
  n19["联华超市-地下室-撬锁"]
  n20["联华超市-地下室-破锁"]
  n21["五金店-暗道"]
  n22["结局-五金店-地铁"]
  n23["五金店-暗道-仓库"]
  n24["五金店-暗道-返回"]
  n25["↔三林路"]:::ext
  n26["↔整理整理"]:::ext
  n0 --> n1
  n0 --> n9
  n0 --> n12
  n1 --> n2
  n1 --> n4
  n2 --> n3
  n4 --> n5
  n4 --> n7
  n5 -.-> n6
  n7 --> n8
  n9 --> n10
  n10 --> n5
  n10 --> n11
  n11 --> n8
  n12 --> n13
  n12 --> n17
  n12 --> n15
  n12 --> n0
  n13 --> n14
  n15 --> n16
  n15 --> n17
  n15 --> n0
  n17 --> n18
  n19 --> n21
  n20 --> n21
  n21 --> n22
  n21 --> n23
  n23 --> n24
  classDef ext fill:#555,color:#ccc;
