flowchart LR
  n0["五金店"]
  n1["五金店-正门"]
  n2["五金店-正门-摸黑"]
  n3["结局-五金店-地沟"]
  n4["五金店-正门-照明"]
  n5["结局-五金店-工具区"]
  n6["结局-五金店-迅捷"]
  n7["五金店-前台"]
  n8["结局-五金店-毒气"]
  n9["五金店-侧窗"]
  n10["五金店-侧窗-探索"]
  n11["五金店-侧窗-拿螺丝刀"]
  n12["五金店-货架躲藏"]
  n13["五金店-后巷"]
  n14["五金店-后巷-撬锁"]
  n15["结局-五金店-开门杀"]
  n16["五金店-后巷-偷看左门"]
  n17["结局-配电房"]
  n18["五金店-后巷-偷看右门"]
  n19["结局-五金店-对视"]
  n20["联华超市-地下室-撬锁"]
  n21["联华超市-地下室-破锁"]
  n22["五金店-暗道"]
  n23["结局-五金店-地铁"]
  n24["五金店-暗道-仓库"]
  n25["五金店-暗道-返回"]
  n26["↔三林路"]:::ext
  n27["↔整理整理"]:::ext
  n0 --> n1
  n0 --> n9
  n0 --> n13
  n1 --> n2
  n1 --> n4
  n2 --> n3
  n4 --> n5
  n4 --> n7
  n5 -.-> n6
  n7 --> n8
  n9 --> n10
  n9 --> n0
  n10 --> n11
  n10 --> n5
  n10 --> n12
  n10 --> n0
  n11 --> n10
  n13 --> n14
  n13 --> n18
  n13 --> n16
  n13 --> n0
  n14 --> n15
  n16 --> n17
  n16 --> n18
  n16 --> n0
  n18 --> n19
  n20 --> n22
  n21 --> n22
  n22 --> n23
  n22 --> n24
  n24 --> n25
  classDef ext fill:#555,color:#ccc;
