flowchart LR
  n0["金谊广场-龙头区"]
  n1["金谊广场-停车场入口"]
  n2["金谊广场-地铁站-地上"]
  n3["金谊广场-龙头区长廊"]
  n4["金谊广场-足球场"]
  n5["金谊广场-吉祥馄饨"]
  n6["金谊广场-吉祥馄饨-聊"]
  n7["金谊广场-吉祥馄饨-看"]
  n8["金谊广场-吉祥馄饨-吃馄饨"]
  n9["金谊广场-地面停车场"]
  n10["金谊广场-吉祥馄饨-杀出去"]
  n11["金谊广场-停车场-救完"]
  n12["金谊广场-停车场-搜刮"]
  n13["金谊广场-停车场-搜刮-拿到水"]
  n14["金谊广场地面入口"]
  n15["金谊广场-正门硬闯"]
  n16["金谊广场-正门硬闯-成功"]
  n17["金谊广场-B2车库入口"]
  n18["金谊广场-B2摸到死路"]
  n19["金谊广场-B2货梯间"]
  n20["金谊广场-地铁站厅"]
  n21["金谊广场-地铁站厅-成功"]
  n22["金谊广场-地铁站厅-失败"]
  n23["金谊广场-1F 门面层"]
  n24["金谊广场-1F肯德基"]
  n25["金谊广场-1F肯德基-吃鸡块"]
  n26["金谊广场-2F"]
  n27["金谊广场-2F-休息"]
  n28["金谊广场-2F-休息-休息完"]
  n29["金谊广场-2F-换装"]
  n30["金谊广场-3F"]
  n31["金谊广场-3F-幸存者"]
  n32["金谊广场-3F-幸存者-聊长廊"]
  n33["金谊广场-3F-幸存者-分食物"]
  n34["金谊广场-4F"]
  n35["金谊广场-4F-影院"]
  n36["金谊广场-4F-影院-吃爆米花"]
  n37["金谊广场-4F-后厨"]
  n38["金谊广场-5F"]
  n39["金谊广场-5F-酒精消毒"]
  n40["金谊广场-B1 心谊如意街"]
  n41["金谊广场-B1奥乐齐"]
  n42["金谊广场-B1奥乐齐-搜刮-吃完"]
  n43["金谊广场-B1童涵春堂"]
  n44["金谊广场-B2 地下车库"]
  n45["金谊广场-B2-搜刮"]
  n46["金谊广场-B2-搜刮-搜完"]
  n47["金谊广场-天台"]
  n48["↔结局-丧尸的围殴"]:::ext
  n49["↔三林路-路霸-堵路"]:::ext
  n50["↔整理整理"]:::ext
  n51["↔结局-被丧尸扑倒咬死"]:::ext
  n52["↔新达汇车库出口"]:::ext
  n53["↔结局-汞中毒尸变"]:::ext
  n54["↔天台-卖药郎中"]:::ext
  n0 --> n3
  n0 --> n9
  n0 --> n2
  n1 --> n9
  n1 --> n2
  n1 --> n14
  n2 --> n20
  n2 --> n4
  n2 --> n0
  n2 --> n1
  n3 --> n0
  n3 --> n30
  n4 --> n2
  n5 --> n6
  n5 --> n7
  n5 --> n8
  n5 --> n9
  n6 --> n10
  n6 --> n9
  n6 --> n7
  n7 --> n6
  n7 --> n5
  n8 --> n5
  n9 --> n12
  n9 --> n5
  n9 --> n0
  n9 --> n1
  n10 --> n11
  n11 --> n9
  n12 --> n13
  n12 --> n9
  n13 --> n9
  n14 --> n15
  n14 --> n17
  n14 --> n1
  n15 --> n16
  n16 --> n23
  n17 --> n18
  n17 --> n44
  n17 --> n14
  n18 --> n17
  n19 --> n17
  n19 --> n23
  n19 --> n44
  n20 --> n21
  n20 -.-> n22
  n20 -.-> n22
  n21 --> n40
  n22 --> n40
  n23 --> n24
  n23 --> n26
  n23 --> n40
  n23 --> n19
  n23 --> n14
  n24 --> n25
  n24 --> n23
  n25 --> n24
  n26 --> n27
  n26 --> n29
  n26 --> n30
  n26 --> n23
  n27 --> n28
  n27 --> n26
  n28 --> n28
  n28 --> n26
  n29 --> n26
  n30 --> n31
  n30 --> n34
  n30 --> n26
  n30 --> n3
  n31 --> n32
  n31 --> n30
  n32 --> n31
  n33 --> n31
  n34 --> n35
  n34 --> n37
  n34 --> n34
  n34 --> n38
  n34 --> n30
  n35 --> n36
  n35 --> n34
  n36 --> n35
  n37 --> n34
  n38 --> n47
  n38 --> n34
  n38 --> n39
  n39 --> n38
  n40 --> n41
  n40 --> n43
  n40 --> n23
  n40 --> n2
  n41 --> n40
  n41 --> n3
  n41 --> n42
  n42 --> n41
  n43 --> n43
  n43 --> n40
  n44 --> n45
  n44 --> n17
  n45 --> n46
  n45 --> n17
  n46 --> n46
  n46 --> n19
  n47 --> n38
  classDef ext fill:#555,color:#ccc;
