flowchart LR
  n0["仁济南院-浦锦路"]
  n1["仁济南院-急诊大门"]
  n2["仁济南院-大门-绷带"]
  n3["仁济南院-门诊大门-记忆闪色"]
  n4["仁济南院-门诊大门-记忆闪色-受伤"]
  n5["仁济南院-门诊大门-记忆闪色-成功"]
  n6["结局-仁济-正门失守"]
  n7["仁济南院-门诊大门"]
  n8["仁济南院-救护车通道"]
  n9["仁济南院-救护车-检查"]
  n10["仁济南院-救护车-倒车撞门"]
  n11["仁济南院-救护车-枪击开锁"]
  n12["仁济南院-救护车-推门"]
  n13["结局-仁济-铁门砸死"]
  n14["仁济南院-地下停车场"]
  n15["仁济南院-地下停车场-深处"]
  n16["仁济南院-地下停车场-惊动丧尸群"]
  n17["仁济南院-地下停车场-踩到碎玻璃"]
  n18["结局-仁济-车库尸群"]
  n19["仁济南院-地下停车场-电梯口"]
  n20["仁济南院-地下停车场-电梯-坏钮"]
  n21["结局-仁济-电梯轿厢"]
  n22["仁济南院-后勤通道"]
  n23["仁济南院-检验科后门"]
  n24["仁济南院-检验科后门-窥视"]
  n25["仁济南院-检验科后门-方瑜"]
  n26["仁济南院-急诊大厅"]
  n27["仁济南院-急诊大厅-战斗"]
  n28["仁济南院-急诊大厅-受伤"]
  n29["仁济南院-急诊大厅-胜利"]
  n30["结局-仁济-急诊失守"]
  n31["仁济南院-门诊药房"]
  n32["仁济南院-门诊药房-抗生素"]
  n33["仁济南院-门诊药房-止痛药"]
  n34["仁济南院-门诊药房-酒精"]
  n35["仁济南院-门诊药房-药丸"]
  n36["仁济南院-检验科"]
  n37["仁济南院-检验科-锁着"]
  n38["仁济南院-检验科-进入"]
  n39["仁济南院-检验科-破门"]
  n40["仁济南院-检验科-撬门"]
  n41["仁济南院-检验科-撬门-失败"]
  n42["仁济南院-检验科-撬开了"]
  n43["仁济南院-检验科-守卫战"]
  n44["仁济南院-检验科-守卫战-受伤"]
  n45["仁济南院-检验科-守卫战-胜利"]
  n46["结局-仁济-检验科被咬"]
  n47["仁济南院-检验科-内部"]
  n48["仁济南院-检验科-手机"]
  n49["仁济南院-检验科-手机-充电"]
  n50["仁济南院-检验科-手机-视频"]
  n51["仁济南院-检验科-记录本"]
  n52["仁济南院-检验科-躲藏"]
  n53["仁济南院-检验科-碘伏"]
  n54["仁济南院-住院部走廊"]
  n55["仁济南院-住院部走廊-战斗"]
  n56["仁济南院-住院部走廊-战斗-受伤"]
  n57["仁济南院-住院部走廊-胜利"]
  n58["结局-仁济-病区失守"]
  n59["仁济南院-住院部走廊-幸存者"]
  n60["仁济南院-住院部走廊-幸存者-救"]
  n61["仁济南院-手术供应室"]
  n62["仁济南院-手术供应室-缝合包"]
  n63["仁济南院-手术供应室-止血带"]
  n64["仁济南院-手术供应室-麻醉剂"]
  n65["仁济南院-手术供应室-躲藏"]
  n66["仁济南院-太平间"]
  n67["仁济南院-太平间-检验科门"]
  n68["仁济南院-太平间-通风"]
  n69["仁济南院-太平间-通风开启"]
  n70["仁济南院-太平间-戴面具"]
  n71["仁济南院-太平间-黑皮丧尸"]
  n72["仁济南院-太平间-黑皮丧尸-受伤"]
  n73["仁济南院-太平间-黑皮丧尸-胜利"]
  n74["结局-仁济-黑皮丧尸"]
  n75["结局-仁济-尸潮围困"]
  n76["结局-仁济-急诊门厅"]
  n77["仁济南院-太平间-报告"]
  n78["仁济南院-门诊大厅"]
  n79["仁济南院-门诊大厅-导览图"]
  n80["仁济南院-电梯厅"]
  n81["结局-仁济-电梯召唤"]
  n82["仁济南院-影像科"]
  n83["仁济南院-输液大厅"]
  n84["仁济南院-中医科"]
  n85["仁济南院-针灸推拿"]
  n86["仁济南院-中草药房"]
  n87["仁济南院-中草药房-喝花茶"]
  n88["仁济南院-急诊观察室"]
  n89["仁济南院-护士站"]
  n90["仁济南院-护士站-喝葡萄糖"]
  n91["仁济南院-楼梯-住院楼"]
  n92["仁济南院-特需病房"]
  n93["仁济南院-特需病房-病床"]
  n94["仁济南院-特需病房-病床-带走"]
  n95["仁济南院-特需病房-病床-空"]
  n96["仁济南院-特需病房-功能饮料"]
  n97["仁济南院-特需病房-病历"]
  n98["仁济南院-特需病房-茶几"]
  n99["仁济南院-特需病房-沙发-偷袭"]
  n100["仁济南院-特需病房-沙发"]
  n101["仁济南院-特需病房-储物柜-警觉"]
  n102["仁济南院-特需病房-储物柜"]
  n103["结局-仁济-特需偷袭"]
  n104["仁济南院-楼梯-急诊楼"]
  n105["仁济南院-楼梯-门诊楼低"]
  n106["仁济南院-楼梯-门诊楼高"]
  n107["↔{_sprintDest}"]:::ext
  n108["↔济阳路跨线桥"]:::ext
  n109["↔整理整理"]:::ext
  n0 --> n7
  n0 --> n1
  n0 --> n14
  n0 -.-> n75
  n1 --> n76
  n1 --> n8
  n1 --> n7
  n2 --> n7
  n3 --> n5
  n3 -.-> n6
  n4 --> n78
  n5 --> n78
  n7 --> n3
  n7 -.-> n78
  n7 --> n2
  n7 --> n0
  n8 --> n9
  n8 --> n12
  n8 --> n0
  n8 --> n26
  n8 --> n10
  n9 --> n8
  n10 --> n8
  n11 --> n8
  n12 --> n8
  n14 --> n15
  n14 --> n0
  n15 --> n14
  n16 --> n19
  n16 -.-> n17
  n16 --> n22
  n16 --> n0
  n16 -.-> n18
  n17 --> n19
  n19 --> n21
  n19 --> n20
  n19 --> n15
  n20 --> n19
  n22 --> n23
  n22 --> n54
  n22 --> n66
  n22 --> n15
  n23 --> n25
  n23 --> n24
  n23 --> n22
  n24 --> n23
  n25 --> n23
  n26 --> n27
  n26 --> n36
  n26 --> n104
  n26 --> n78
  n26 --> n54
  n26 --> n8
  n26 -.-> n27
  n27 --> n29
  n27 -.-> n30
  n28 --> n26
  n29 --> n26
  n31 --> n32
  n31 --> n33
  n31 --> n34
  n31 --> n35
  n31 --> n78
  n32 --> n31
  n33 --> n31
  n34 --> n31
  n35 --> n31
  n36 --> n47
  n36 --> n38
  n36 --> n39
  n36 --> n40
  n36 --> n37
  n36 --> n26
  n37 --> n26
  n38 --> n43
  n39 --> n43
  n40 --> n42
  n40 --> n36
  n40 --> n41
  n41 --> n40
  n41 --> n36
  n42 --> n43
  n43 --> n45
  n43 -.-> n46
  n44 --> n47
  n45 --> n47
  n47 --> n48
  n47 --> n52
  n47 --> n51
  n47 --> n53
  n47 --> n61
  n47 --> n66
  n47 --> n36
  n48 --> n50
  n48 --> n49
  n48 --> n47
  n49 --> n50
  n49 --> n47
  n50 --> n47
  n51 --> n47
  n52 --> n47
  n53 --> n53
  n53 --> n47
  n54 --> n55
  n54 --> n59
  n54 --> n89
  n54 --> n91
  n54 --> n26
  n55 --> n57
  n55 -.-> n58
  n56 --> n54
  n57 --> n54
  n59 --> n60
  n59 --> n54
  n60 --> n54
  n61 --> n62
  n61 --> n63
  n61 --> n64
  n61 --> n47
  n61 --> n65
  n62 --> n61
  n63 --> n61
  n64 --> n61
  n65 --> n61
  n66 --> n71
  n66 --> n70
  n66 --> n68
  n66 --> n77
  n66 --> n22
  n66 --> n47
  n66 -.-> n67
  n67 --> n66
  n68 --> n69
  n68 --> n66
  n69 --> n66
  n70 --> n71
  n71 --> n73
  n71 -.-> n74
  n72 --> n66
  n73 --> n66
  n77 --> n66
  n78 --> n79
  n78 --> n80
  n78 --> n105
  n78 --> n26
  n78 --> n7
  n79 --> n31
  n79 --> n82
  n79 --> n78
  n80 --> n83
  n80 --> n84
  n80 --> n81
  n80 --> n78
  n82 --> n78
  n83 --> n88
  n83 --> n80
  n83 --> n106
  n83 --> n105
  n84 --> n85
  n84 --> n86
  n84 --> n80
  n84 --> n106
  n85 --> n86
  n85 --> n84
  n86 --> n87
  n86 --> n84
  n86 --> n85
  n87 --> n86
  n88 --> n83
  n88 --> n104
  n89 --> n90
  n89 --> n54
  n90 --> n89
  n91 --> n92
  n91 --> n54
  n92 --> n93
  n92 --> n97
  n92 --> n99
  n92 --> n98
  n92 --> n103
  n92 --> n91
  n92 --> n100
  n92 --> n102
  n92 --> n95
  n92 --> n101
  n93 --> n96
  n93 --> n94
  n93 --> n92
  n94 --> n92
  n95 --> n92
  n96 --> n92
  n97 --> n92
  n98 --> n92
  n99 --> n100
  n99 --> n92
  n100 --> n92
  n101 --> n92
  n102 --> n92
  n104 --> n88
  n104 --> n26
  n105 --> n83
  n105 --> n78
  n106 --> n84
  n106 --> n83
  classDef ext fill:#555,color:#ccc;
