flowchart LR
  n0["仁济南院-浦锦路"]
  n1["仁济南院-急诊大门"]
  n2["仁济南院-大门-绷带"]
  n3["仁济南院-门诊大门-记忆闪色"]
  n4["仁济南院-门诊大门-记忆闪色-成功"]
  n5["结局-仁济-正门失守"]
  n6["仁济南院-门诊大门"]
  n7["仁济南院-救护车通道"]
  n8["仁济南院-救护车-检查"]
  n9["仁济南院-救护车-倒车撞门"]
  n10["仁济南院-救护车-枪击开锁"]
  n11["仁济南院-救护车-推门"]
  n12["结局-仁济-铁门砸死"]
  n13["仁济南院-地下停车场"]
  n14["仁济南院-地下停车场-深处"]
  n15["仁济南院-地下停车场-惊动丧尸群"]
  n16["仁济南院-地下停车场-踩到碎玻璃"]
  n17["结局-仁济-车库尸群"]
  n18["仁济南院-地下停车场-电梯口"]
  n19["仁济南院-地下停车场-电梯-坏钮"]
  n20["结局-仁济-电梯轿厢"]
  n21["仁济南院-后勤通道"]
  n22["仁济南院-检验科后门"]
  n23["仁济南院-检验科后门-窥视"]
  n24["仁济南院-检验科后门-方瑜"]
  n25["仁济南院-急诊大厅"]
  n26["仁济南院-急诊大厅-战斗"]
  n27["仁济南院-急诊大厅-胜利"]
  n28["结局-仁济-急诊失守"]
  n29["仁济南院-门诊药房"]
  n30["仁济南院-门诊药房-抗生素"]
  n31["仁济南院-门诊药房-止痛药"]
  n32["仁济南院-门诊药房-酒精"]
  n33["仁济南院-门诊药房-药丸"]
  n34["仁济南院-检验科"]
  n35["仁济南院-检验科-锁着"]
  n36["仁济南院-检验科-进入"]
  n37["仁济南院-检验科-破门"]
  n38["仁济南院-检验科-撬门"]
  n39["仁济南院-检验科-撬门-失败"]
  n40["仁济南院-检验科-撬开了"]
  n41["仁济南院-检验科-守卫战"]
  n42["仁济南院-检验科-守卫战-胜利"]
  n43["结局-仁济-检验科被咬"]
  n44["仁济南院-检验科-内部"]
  n45["仁济南院-检验科-手机"]
  n46["仁济南院-检验科-手机-充电"]
  n47["仁济南院-检验科-手机-视频"]
  n48["仁济南院-检验科-记录本"]
  n49["仁济南院-检验科-躲藏"]
  n50["仁济南院-检验科-碘伏"]
  n51["仁济南院-住院部走廊"]
  n52["仁济南院-住院部走廊-战斗"]
  n53["仁济南院-住院部走廊-胜利"]
  n54["结局-仁济-病区失守"]
  n55["仁济南院-住院部走廊-幸存者"]
  n56["仁济南院-住院部走廊-幸存者-救"]
  n57["仁济南院-手术供应室"]
  n58["仁济南院-手术供应室-缝合包"]
  n59["仁济南院-手术供应室-止血带"]
  n60["仁济南院-手术供应室-麻醉剂"]
  n61["仁济南院-手术供应室-躲藏"]
  n62["仁济南院-太平间"]
  n63["仁济南院-太平间-检验科门"]
  n64["仁济南院-太平间-通风"]
  n65["仁济南院-太平间-通风开启"]
  n66["仁济南院-太平间-戴面具"]
  n67["仁济南院-太平间-黑皮丧尸"]
  n68["仁济南院-太平间-黑皮丧尸-胜利"]
  n69["结局-仁济-黑皮丧尸"]
  n70["结局-仁济-尸潮围困"]
  n71["结局-仁济-急诊门厅"]
  n72["仁济南院-太平间-报告"]
  n73["仁济南院-门诊大厅"]
  n74["仁济南院-门诊大厅-导览图"]
  n75["仁济南院-电梯厅"]
  n76["结局-仁济-电梯召唤"]
  n77["仁济南院-影像科"]
  n78["仁济南院-输液大厅"]
  n79["仁济南院-中医科"]
  n80["仁济南院-针灸推拿"]
  n81["仁济南院-中草药房"]
  n82["仁济南院-中草药房-喝花茶"]
  n83["仁济南院-急诊观察室"]
  n84["仁济南院-护士站"]
  n85["仁济南院-护士站-喝葡萄糖"]
  n86["仁济南院-楼梯-住院楼"]
  n87["仁济南院-特需病房"]
  n88["仁济南院-特需病房-病床"]
  n89["仁济南院-特需病房-病床-带走"]
  n90["仁济南院-特需病房-病床-空"]
  n91["仁济南院-特需病房-功能饮料"]
  n92["仁济南院-特需病房-病历"]
  n93["仁济南院-特需病房-茶几"]
  n94["仁济南院-特需病房-沙发-偷袭"]
  n95["仁济南院-特需病房-沙发"]
  n96["仁济南院-特需病房-储物柜-警觉"]
  n97["仁济南院-特需病房-储物柜"]
  n98["结局-仁济-特需偷袭"]
  n99["仁济南院-楼梯-急诊楼"]
  n100["仁济南院-楼梯-门诊楼低"]
  n101["仁济南院-楼梯-门诊楼高"]
  n102["↔{_sprintDest}"]:::ext
  n103["↔济阳路跨线桥"]:::ext
  n104["↔整理整理"]:::ext
  n0 --> n6
  n0 --> n1
  n0 --> n13
  n0 -.-> n70
  n1 --> n71
  n1 --> n7
  n1 --> n6
  n2 --> n6
  n3 --> n4
  n3 -.-> n5
  n3 -.-> n5
  n4 --> n73
  n6 --> n3
  n6 -.-> n73
  n6 --> n2
  n6 --> n0
  n7 --> n8
  n7 --> n11
  n7 --> n0
  n7 --> n25
  n7 --> n9
  n8 --> n7
  n9 --> n7
  n10 --> n7
  n11 --> n7
  n13 --> n14
  n13 --> n0
  n14 --> n13
  n15 --> n18
  n15 -.-> n16
  n15 --> n21
  n15 --> n0
  n15 -.-> n17
  n16 --> n18
  n18 --> n20
  n18 --> n19
  n18 --> n14
  n19 --> n18
  n21 --> n22
  n21 --> n51
  n21 --> n62
  n21 --> n14
  n22 --> n24
  n22 --> n23
  n22 --> n21
  n23 --> n22
  n24 --> n22
  n25 --> n26
  n25 --> n34
  n25 --> n99
  n25 --> n73
  n25 --> n51
  n25 --> n7
  n25 -.-> n26
  n26 --> n27
  n26 -.-> n28
  n26 -.-> n28
  n27 --> n25
  n29 --> n30
  n29 --> n31
  n29 --> n32
  n29 --> n33
  n29 --> n73
  n30 --> n29
  n31 --> n29
  n32 --> n29
  n33 --> n29
  n34 --> n44
  n34 --> n36
  n34 --> n37
  n34 --> n38
  n34 --> n35
  n34 --> n25
  n35 --> n25
  n36 --> n41
  n37 --> n41
  n38 --> n39
  n38 --> n34
  n38 --> n40
  n39 --> n38
  n39 --> n34
  n40 --> n41
  n41 --> n42
  n41 -.-> n43
  n41 -.-> n43
  n42 --> n44
  n44 --> n45
  n44 --> n49
  n44 --> n48
  n44 --> n50
  n44 --> n57
  n44 --> n62
  n44 --> n34
  n45 --> n47
  n45 --> n46
  n45 --> n44
  n46 --> n47
  n46 --> n44
  n47 --> n44
  n48 --> n44
  n49 --> n44
  n50 --> n50
  n50 --> n44
  n51 --> n52
  n51 --> n55
  n51 --> n84
  n51 --> n86
  n51 --> n25
  n52 --> n53
  n52 -.-> n54
  n52 -.-> n54
  n53 --> n51
  n55 --> n56
  n55 --> n51
  n56 --> n51
  n57 --> n58
  n57 --> n59
  n57 --> n60
  n57 --> n44
  n57 --> n61
  n58 --> n57
  n59 --> n57
  n60 --> n57
  n61 --> n57
  n62 --> n67
  n62 --> n66
  n62 --> n64
  n62 --> n72
  n62 --> n21
  n62 --> n44
  n62 -.-> n63
  n63 --> n62
  n64 --> n65
  n64 --> n62
  n65 --> n62
  n66 --> n67
  n67 --> n68
  n67 -.-> n69
  n67 -.-> n69
  n68 --> n62
  n72 --> n62
  n73 --> n74
  n73 --> n75
  n73 --> n100
  n73 --> n25
  n73 --> n6
  n74 --> n29
  n74 --> n77
  n74 --> n73
  n75 --> n78
  n75 --> n79
  n75 --> n76
  n75 --> n73
  n77 --> n73
  n78 --> n83
  n78 --> n75
  n78 --> n101
  n78 --> n100
  n79 --> n80
  n79 --> n81
  n79 --> n75
  n79 --> n101
  n80 --> n81
  n80 --> n79
  n81 --> n82
  n81 --> n79
  n81 --> n80
  n82 --> n81
  n83 --> n78
  n83 --> n99
  n84 --> n85
  n84 --> n51
  n85 --> n84
  n86 --> n87
  n86 --> n51
  n87 --> n88
  n87 --> n92
  n87 --> n94
  n87 --> n93
  n87 --> n98
  n87 --> n86
  n87 --> n95
  n87 --> n97
  n87 --> n90
  n87 --> n96
  n88 --> n91
  n88 --> n89
  n88 --> n87
  n89 --> n87
  n90 --> n87
  n91 --> n87
  n92 --> n87
  n93 --> n87
  n94 --> n95
  n94 --> n87
  n95 --> n87
  n96 --> n87
  n97 --> n87
  n99 --> n83
  n99 --> n25
  n100 --> n78
  n100 --> n73
  n101 --> n79
  n101 --> n78
  classDef ext fill:#555,color:#ccc;
