flowchart LR
  n0["仁济南院-浦锦路"]
  n1["仁济南院-急诊大门"]
  n2["仁济南院-大门-绷带"]
  n3["仁济南院-门诊大门-记忆闪色"]
  n4["仁济南院-门诊大门-记忆闪色-成功"]
  n5["结局-仁济-正门失守"]
  n6["仁济南院-门诊大门"]
  n7["仁济南院-救护车通道"]
  n8["仁济南院-救护车-检查"]
  n9["仁济南院-救护车-倒车撞门"]
  n10["仁济南院-救护车-枪击开锁"]
  n11["仁济南院-救护车-推门"]
  n12["结局-仁济-铁门砸死"]
  n13["仁济南院-地下停车场"]
  n14["仁济南院-地下停车场-电梯口"]
  n15["仁济南院-地下停车场-电梯-坏钮"]
  n16["结局-仁济-电梯轿厢"]
  n17["仁济南院-后勤通道"]
  n18["仁济南院-检验科后门"]
  n19["仁济南院-检验科后门-窥视"]
  n20["仁济南院-检验科后门-方瑜"]
  n21["仁济南院-急诊大厅"]
  n22["仁济南院-急诊大厅-战斗"]
  n23["仁济南院-急诊大厅-胜利"]
  n24["结局-仁济-急诊失守"]
  n25["仁济南院-门诊药房"]
  n26["仁济南院-门诊药房-抗生素"]
  n27["仁济南院-门诊药房-止痛药"]
  n28["仁济南院-门诊药房-酒精"]
  n29["仁济南院-门诊药房-药丸"]
  n30["仁济南院-检验科"]
  n31["仁济南院-检验科-锁着"]
  n32["仁济南院-检验科-进入"]
  n33["仁济南院-检验科-破门"]
  n34["仁济南院-检验科-撬门"]
  n35["仁济南院-检验科-撬门-失败"]
  n36["仁济南院-检验科-撬开了"]
  n37["仁济南院-检验科-守卫战"]
  n38["仁济南院-检验科-守卫战-胜利"]
  n39["结局-仁济-检验科被咬"]
  n40["仁济南院-检验科-内部"]
  n41["仁济南院-检验科-手机"]
  n42["仁济南院-检验科-手机-充电"]
  n43["仁济南院-检验科-手机-视频"]
  n44["仁济南院-检验科-记录本"]
  n45["仁济南院-检验科-躲藏"]
  n46["仁济南院-检验科-碘伏"]
  n47["仁济南院-住院部走廊"]
  n48["仁济南院-住院部走廊-战斗"]
  n49["仁济南院-住院部走廊-胜利"]
  n50["结局-仁济-病区失守"]
  n51["仁济南院-住院部走廊-幸存者"]
  n52["仁济南院-住院部走廊-幸存者-救"]
  n53["仁济南院-手术供应室"]
  n54["仁济南院-手术供应室-缝合包"]
  n55["仁济南院-手术供应室-止血带"]
  n56["仁济南院-手术供应室-麻醉剂"]
  n57["仁济南院-手术供应室-躲藏"]
  n58["仁济南院-太平间"]
  n59["仁济南院-太平间-检验科门"]
  n60["仁济南院-太平间-通风"]
  n61["仁济南院-太平间-通风开启"]
  n62["仁济南院-太平间-戴面具"]
  n63["仁济南院-太平间-黑皮丧尸"]
  n64["仁济南院-太平间-黑皮丧尸-胜利"]
  n65["结局-仁济-黑皮丧尸"]
  n66["结局-仁济-尸潮围困"]
  n67["结局-仁济-急诊门厅"]
  n68["仁济南院-太平间-报告"]
  n69["仁济南院-门诊大厅"]
  n70["仁济南院-门诊大厅-导览图"]
  n71["仁济南院-电梯厅"]
  n72["结局-仁济-电梯召唤"]
  n73["仁济南院-影像科"]
  n74["仁济南院-输液大厅"]
  n75["仁济南院-中医科"]
  n76["仁济南院-针灸推拿"]
  n77["仁济南院-中草药房"]
  n78["仁济南院-中草药房-喝花茶"]
  n79["仁济南院-急诊观察室"]
  n80["仁济南院-护士站"]
  n81["仁济南院-护士站-喝葡萄糖"]
  n82["仁济南院-楼梯-住院楼"]
  n83["仁济南院-特需病房"]
  n84["仁济南院-特需病房-病床"]
  n85["仁济南院-特需病房-病床-带走"]
  n86["仁济南院-特需病房-病床-空"]
  n87["仁济南院-特需病房-功能饮料"]
  n88["仁济南院-特需病房-病历"]
  n89["仁济南院-特需病房-茶几"]
  n90["仁济南院-特需病房-沙发-偷袭"]
  n91["仁济南院-特需病房-沙发"]
  n92["仁济南院-特需病房-储物柜-警觉"]
  n93["仁济南院-特需病房-储物柜"]
  n94["结局-仁济-特需偷袭"]
  n95["仁济南院-楼梯-急诊楼"]
  n96["仁济南院-楼梯-门诊楼低"]
  n97["仁济南院-楼梯-门诊楼高"]
  n98["↔{_sprintDest}"]:::ext
  n99["↔济阳路跨线桥"]:::ext
  n100["↔整理整理"]:::ext
  n0 --> n6
  n0 --> n1
  n0 --> n13
  n0 -.-> n66
  n1 --> n67
  n1 --> n7
  n1 --> n6
  n2 --> n6
  n3 --> n4
  n3 -.-> n5
  n3 -.-> n5
  n4 --> n69
  n6 --> n3
  n6 -.-> n69
  n6 --> n2
  n6 --> n0
  n7 --> n8
  n7 --> n11
  n7 --> n0
  n7 --> n21
  n7 --> n9
  n8 --> n7
  n9 --> n7
  n10 --> n7
  n11 --> n7
  n13 --> n17
  n13 --> n14
  n13 --> n0
  n14 --> n16
  n14 --> n15
  n14 --> n13
  n15 --> n14
  n17 --> n18
  n17 --> n47
  n17 --> n58
  n17 --> n13
  n18 --> n20
  n18 --> n19
  n18 --> n17
  n19 --> n18
  n20 --> n18
  n21 --> n22
  n21 --> n30
  n21 --> n95
  n21 --> n69
  n21 --> n47
  n21 --> n7
  n21 -.-> n22
  n22 --> n23
  n22 -.-> n24
  n22 -.-> n24
  n23 --> n21
  n25 --> n26
  n25 --> n27
  n25 --> n28
  n25 --> n29
  n25 --> n69
  n26 --> n25
  n27 --> n25
  n28 --> n25
  n29 --> n25
  n30 --> n40
  n30 --> n32
  n30 --> n33
  n30 --> n34
  n30 --> n31
  n30 --> n21
  n31 --> n21
  n32 --> n37
  n33 --> n37
  n34 --> n35
  n34 --> n30
  n34 --> n36
  n35 --> n34
  n35 --> n30
  n36 --> n37
  n37 --> n38
  n37 -.-> n39
  n37 -.-> n39
  n38 --> n40
  n40 --> n41
  n40 --> n45
  n40 --> n44
  n40 --> n46
  n40 --> n53
  n40 --> n58
  n40 --> n30
  n41 --> n43
  n41 --> n42
  n41 --> n40
  n42 --> n43
  n42 --> n40
  n43 --> n40
  n44 --> n40
  n45 --> n40
  n46 --> n46
  n46 --> n40
  n47 --> n48
  n47 --> n51
  n47 --> n80
  n47 --> n82
  n47 --> n21
  n48 --> n49
  n48 -.-> n50
  n48 -.-> n50
  n49 --> n47
  n51 --> n52
  n51 --> n47
  n52 --> n47
  n53 --> n54
  n53 --> n55
  n53 --> n56
  n53 --> n40
  n53 --> n57
  n54 --> n53
  n55 --> n53
  n56 --> n53
  n57 --> n53
  n58 --> n63
  n58 --> n62
  n58 --> n60
  n58 --> n68
  n58 --> n17
  n58 --> n40
  n58 -.-> n59
  n59 --> n58
  n60 --> n61
  n60 --> n58
  n61 --> n58
  n62 --> n63
  n63 --> n64
  n63 -.-> n65
  n63 -.-> n65
  n64 --> n58
  n68 --> n58
  n69 --> n70
  n69 --> n71
  n69 --> n96
  n69 --> n21
  n69 --> n6
  n70 --> n25
  n70 --> n73
  n70 --> n69
  n71 --> n74
  n71 --> n75
  n71 --> n72
  n71 --> n69
  n73 --> n69
  n74 --> n79
  n74 --> n71
  n74 --> n97
  n74 --> n96
  n75 --> n76
  n75 --> n77
  n75 --> n71
  n75 --> n97
  n76 --> n77
  n76 --> n75
  n77 --> n78
  n77 --> n75
  n77 --> n76
  n78 --> n77
  n79 --> n74
  n79 --> n95
  n80 --> n81
  n80 --> n47
  n81 --> n80
  n82 --> n83
  n82 --> n47
  n83 --> n84
  n83 --> n88
  n83 --> n90
  n83 --> n89
  n83 --> n94
  n83 --> n82
  n83 --> n91
  n83 --> n93
  n83 --> n86
  n83 --> n92
  n84 --> n87
  n84 --> n85
  n84 --> n83
  n85 --> n83
  n86 --> n83
  n87 --> n83
  n88 --> n83
  n89 --> n83
  n90 --> n91
  n90 --> n83
  n91 --> n83
  n92 --> n83
  n93 --> n83
  n95 --> n79
  n95 --> n21
  n96 --> n74
  n96 --> n69
  n97 --> n75
  n97 --> n74
  classDef ext fill:#555,color:#ccc;
