flowchart LR
  n0["仁济南院-浦锦路"]
  n1["仁济南院-急诊大门"]
  n2["仁济南院-大门-绷带"]
  n3["仁济南院-门诊大门-记忆闪色"]
  n4["仁济南院-门诊大门-记忆闪色-成功"]
  n5["仁济南院-门诊大门-记忆闪色-失败"]
  n6["仁济南院-门诊大门"]
  n7["仁济南院-救护车通道"]
  n8["仁济南院-救护车-检查"]
  n9["仁济南院-救护车-倒车撞门"]
  n10["仁济南院-救护车-枪击开锁"]
  n11["仁济南院-救护车-推门"]
  n12["结局-仁济-铁门砸死"]
  n13["仁济南院-地下停车场"]
  n14["仁济南院-地下停车场-电梯口"]
  n15["仁济南院-地下停车场-电梯-坏钮"]
  n16["结局-仁济-电梯轿厢"]
  n17["仁济南院-后勤通道"]
  n18["仁济南院-检验科后门"]
  n19["仁济南院-检验科后门-窥视"]
  n20["仁济南院-检验科后门-方瑜"]
  n21["仁济南院-急诊大厅"]
  n22["仁济南院-急诊大厅-战斗"]
  n23["仁济南院-急诊大厅-胜利"]
  n24["仁济南院-急诊大厅-受伤"]
  n25["仁济南院-门诊药房"]
  n26["仁济南院-门诊药房-抗生素"]
  n27["仁济南院-门诊药房-止痛药"]
  n28["仁济南院-门诊药房-酒精"]
  n29["仁济南院-检验科"]
  n30["仁济南院-检验科-锁着"]
  n31["仁济南院-检验科-进入"]
  n32["仁济南院-检验科-破门"]
  n33["仁济南院-检验科-撬门"]
  n34["仁济南院-检验科-撬门-失败"]
  n35["仁济南院-检验科-撬开了"]
  n36["仁济南院-检验科-守卫战"]
  n37["仁济南院-检验科-守卫战-胜利"]
  n38["仁济南院-检验科-守卫战-受伤"]
  n39["仁济南院-检验科-内部"]
  n40["仁济南院-检验科-手机"]
  n41["仁济南院-检验科-手机-充电"]
  n42["仁济南院-检验科-手机-视频"]
  n43["仁济南院-检验科-记录本"]
  n44["仁济南院-检验科-躲藏"]
  n45["仁济南院-检验科-碘伏"]
  n46["仁济南院-住院部走廊"]
  n47["仁济南院-住院部走廊-战斗"]
  n48["仁济南院-住院部走廊-胜利"]
  n49["仁济南院-住院部走廊-受伤"]
  n50["仁济南院-住院部走廊-幸存者"]
  n51["仁济南院-住院部走廊-幸存者-救"]
  n52["仁济南院-手术供应室"]
  n53["仁济南院-手术供应室-缝合包"]
  n54["仁济南院-手术供应室-止血带"]
  n55["仁济南院-手术供应室-麻醉剂"]
  n56["仁济南院-手术供应室-躲藏"]
  n57["仁济南院-太平间"]
  n58["仁济南院-太平间-检验科门"]
  n59["仁济南院-太平间-通风"]
  n60["仁济南院-太平间-通风开启"]
  n61["仁济南院-太平间-戴面具"]
  n62["仁济南院-太平间-黑皮丧尸"]
  n63["仁济南院-太平间-黑皮丧尸-胜利"]
  n64["仁济南院-太平间-黑皮丧尸-受伤"]
  n65["结局-仁济-尸潮围困"]
  n66["结局-仁济-急诊门厅"]
  n67["仁济南院-太平间-报告"]
  n68["仁济南院-门诊大厅"]
  n69["仁济南院-门诊大厅-导览图"]
  n70["仁济南院-电梯厅"]
  n71["结局-仁济-电梯召唤"]
  n72["仁济南院-影像科"]
  n73["仁济南院-输液大厅"]
  n74["仁济南院-中医科"]
  n75["仁济南院-针灸推拿"]
  n76["仁济南院-中草药房"]
  n77["仁济南院-中草药房-喝花茶"]
  n78["仁济南院-急诊观察室"]
  n79["仁济南院-护士站"]
  n80["仁济南院-护士站-喝葡萄糖"]
  n81["仁济南院-楼梯-住院楼"]
  n82["仁济南院-特需病房"]
  n83["仁济南院-特需病房-病床"]
  n84["仁济南院-特需病房-病床-空"]
  n85["仁济南院-特需病房-功能饮料"]
  n86["仁济南院-特需病房-病历"]
  n87["仁济南院-特需病房-茶几"]
  n88["仁济南院-特需病房-沙发-偷袭"]
  n89["仁济南院-特需病房-沙发"]
  n90["仁济南院-特需病房-储物柜-警觉"]
  n91["仁济南院-特需病房-储物柜"]
  n92["结局-仁济-特需偷袭"]
  n93["仁济南院-楼梯-急诊楼"]
  n94["仁济南院-楼梯-门诊楼低"]
  n95["仁济南院-楼梯-门诊楼高"]
  n96["↔{_sprintDest}"]:::ext
  n97["↔济阳路跨线桥"]:::ext
  n98["↔整理整理"]:::ext
  n0 --> n6
  n0 --> n1
  n0 --> n13
  n0 -.-> n65
  n1 --> n66
  n1 --> n7
  n1 --> n6
  n2 --> n6
  n3 --> n4
  n3 -.-> n5
  n3 -.-> n5
  n4 --> n68
  n5 --> n68
  n6 --> n3
  n6 -.-> n68
  n6 --> n2
  n6 --> n0
  n7 --> n8
  n7 --> n11
  n7 --> n0
  n7 --> n21
  n7 --> n9
  n8 --> n7
  n9 --> n7
  n10 --> n7
  n11 --> n7
  n13 --> n17
  n13 --> n14
  n13 --> n0
  n14 --> n16
  n14 --> n15
  n14 --> n13
  n15 --> n14
  n17 --> n18
  n17 --> n46
  n17 --> n57
  n17 --> n13
  n18 --> n20
  n18 --> n19
  n18 --> n17
  n19 --> n18
  n20 --> n18
  n21 --> n22
  n21 --> n29
  n21 --> n93
  n21 --> n68
  n21 --> n46
  n21 --> n7
  n21 -.-> n22
  n22 --> n23
  n22 -.-> n24
  n22 -.-> n24
  n23 --> n21
  n24 --> n21
  n25 --> n26
  n25 --> n27
  n25 --> n28
  n25 --> n68
  n26 --> n25
  n27 --> n25
  n28 --> n25
  n29 --> n39
  n29 --> n31
  n29 --> n32
  n29 --> n33
  n29 --> n30
  n29 --> n21
  n30 --> n21
  n31 --> n36
  n32 --> n36
  n33 --> n34
  n33 --> n29
  n33 --> n35
  n34 --> n33
  n34 --> n29
  n35 --> n36
  n36 --> n37
  n36 -.-> n38
  n36 -.-> n38
  n37 --> n39
  n38 --> n39
  n39 --> n40
  n39 --> n44
  n39 --> n43
  n39 --> n45
  n39 --> n52
  n39 --> n57
  n39 --> n29
  n40 --> n42
  n40 --> n41
  n40 --> n39
  n41 --> n42
  n41 --> n39
  n42 --> n39
  n43 --> n39
  n44 --> n39
  n45 --> n45
  n45 --> n39
  n46 --> n47
  n46 --> n50
  n46 --> n79
  n46 --> n81
  n46 --> n21
  n47 --> n48
  n47 -.-> n49
  n47 -.-> n49
  n48 --> n46
  n49 --> n46
  n50 --> n51
  n50 --> n46
  n51 --> n46
  n52 --> n53
  n52 --> n54
  n52 --> n55
  n52 --> n39
  n52 --> n56
  n53 --> n52
  n54 --> n52
  n55 --> n52
  n56 --> n52
  n57 --> n62
  n57 --> n61
  n57 --> n59
  n57 --> n67
  n57 --> n17
  n57 --> n39
  n57 -.-> n58
  n58 --> n57
  n59 --> n60
  n59 --> n57
  n60 --> n57
  n61 --> n62
  n62 --> n63
  n62 -.-> n64
  n62 -.-> n64
  n63 --> n57
  n64 --> n57
  n67 --> n57
  n68 --> n69
  n68 --> n70
  n68 --> n94
  n68 --> n21
  n68 --> n6
  n69 --> n25
  n69 --> n72
  n69 --> n68
  n70 --> n73
  n70 --> n74
  n70 --> n71
  n70 --> n68
  n72 --> n68
  n73 --> n78
  n73 --> n70
  n73 --> n95
  n73 --> n94
  n74 --> n75
  n74 --> n76
  n74 --> n70
  n74 --> n95
  n75 --> n76
  n75 --> n74
  n76 --> n77
  n76 --> n74
  n76 --> n75
  n77 --> n76
  n78 --> n73
  n78 --> n93
  n79 --> n80
  n79 --> n46
  n80 --> n79
  n81 --> n82
  n81 --> n46
  n82 --> n83
  n82 --> n86
  n82 --> n88
  n82 --> n87
  n82 --> n92
  n82 --> n81
  n82 --> n89
  n82 --> n91
  n82 --> n84
  n82 --> n90
  n83 --> n85
  n83 --> n82
  n84 --> n82
  n85 --> n82
  n86 --> n82
  n87 --> n82
  n88 --> n89
  n88 --> n82
  n89 --> n82
  n90 --> n82
  n91 --> n82
  n93 --> n78
  n93 --> n21
  n94 --> n73
  n94 --> n68
  n95 --> n74
  n95 --> n73
  classDef ext fill:#555,color:#ccc;
