flowchart LR
  n0["复旦江湾-校门"]
  n1["复旦江湾-中央草坪"]
  n2["复旦江湾-材料楼-门前"]
  n3["复旦江湾-材料楼-展板"]
  n4["复旦江湾-环境科学楼-门厅"]
  n5["复旦江湾-环境科学楼-楼梯"]
  n6["复旦江湾-环境科学楼-305"]
  n7["复旦江湾-环境科学楼-305-合影"]
  n8["复旦江湾-环境科学楼-305-出示"]
  n9["复旦江湾-返程车程"]
  n10["复旦江湾-返程车程-出示"]
  n11["复旦江湾-返程车程-空口安慰"]
  n12["复旦江湾-电话叫人"]
  n13["建平-教师小区门口"]
  n14["忻老师家-楼道"]
  n15["忻老师家-家中"]
  n16["忻老师家-楼道-堵门"]
  n17["忻老师家-翻窗双逃"]
  n18["忻老师家-学生救场"]
  n19["忻老师家-学生救场-战斗"]
  n20["忻老师家-学生救场-胜利"]
  n21["回建平-车程"]
  n22["结局-变了的忻老师"]
  n23["↔建平-校园门口"]:::ext
  n24["↔结局-丧尸的围殴"]:::ext
  n25["↔结局-被丧尸扑倒咬死"]:::ext
  n0 --> n1
  n1 --> n2
  n1 --> n4
  n1 --> n0
  n1 --> n9
  n2 --> n3
  n2 --> n1
  n3 --> n2
  n4 --> n5
  n4 --> n1
  n4 --> n6
  n5 --> n6
  n6 --> n7
  n6 --> n8
  n6 --> n4
  n7 --> n6
  n8 --> n6
  n9 --> n12
  n9 --> n10
  n9 --> n11
  n9 --> n13
  n10 --> n13
  n11 --> n9
  n12 --> n12
  n13 --> n14
  n13 --> n12
  n14 --> n15
  n14 --> n13
  n14 --> n12
  n15 --> n16
  n15 --> n18
  n16 --> n21
  n17 --> n21
  n18 --> n19
  n19 --> n20
  n20 --> n21
  classDef ext fill:#555,color:#ccc;
