flowchart LR
  n0["复旦江湾-校门"]
  n1["复旦江湾-中央草坪"]
  n2["复旦江湾-材料楼-门前"]
  n3["复旦江湾-环境科学楼-门厅"]
  n4["复旦江湾-环境科学楼-305"]
  n5["复旦江湾-环境科学楼-305-合影"]
  n6["复旦江湾-返程车程"]
  n7["建平-教师小区门口"]
  n8["忻老师家-楼道"]
  n9["忻老师家-家中"]
  n10["忻老师家-楼道-堵门"]
  n11["忻老师家-翻窗双逃"]
  n12["忻老师家-学生救场"]
  n13["回建平-车程"]
  n14["↔建平-校园门口"]:::ext
  n0 --> n1
  n1 --> n2
  n1 --> n3
  n1 --> n0
  n1 --> n6
  n2 --> n1
  n3 --> n4
  n3 --> n1
  n4 --> n5
  n4 --> n3
  n5 --> n4
  n6 -.-> n7
  n7 --> n8
  n8 --> n9
  n8 --> n7
  n9 --> n10
  n9 --> n12
  n10 --> n13
  n11 --> n13
  n12 --> n13
  classDef ext fill:#555,color:#ccc;
