flowchart LR
  n0["天黑必须过夜"]
  n1["过夜-理发店"]
  n2["过夜-前往理发店"]
  n3["过夜-理发店流浪"]
  n4["过夜-全家"]
  n5["过夜-小超市"]
  n6["过夜-安居苑"]
  n7["过夜-自己家"]
  n8["过夜-车内"]
  n9["过夜-街头兜底"]
  n10["过夜-哥哥的深夜食堂"]
  n11["过夜-金谊广场"]
  n12["结局-过夜-街头死亡"]
  n13["过夜-图书馆"]
  n14["临时的避难所"]
  n15["结局-过夜-自己家不再安全"]
  n16["结局-过夜-全家丧尸还在"]
  n17["结局-过夜-小超市暴露"]
  n18["结局-过夜-图书馆未清理"]
  n19["结局-过夜-深夜食堂上锁"]
  n20["过夜-仁济-检验科"]
  n21["过夜-仁济-药房"]
  n22["过夜-仁济-病房"]
  n23["过夜-仁济-摸黑离开"]
  n24["结局-仁济-摸黑离开失败"]
  n25["结局-仁济-检验科失守"]
  n26["过夜-建平宿舍"]
  n27["结局-过夜-建平教室"]
  n28["结局-过夜-建平街头"]
  n29["结局-过夜-建平宿舍遇袭"]
  n30["过夜-张江-机房"]
  n31["过夜-张江-动力站"]
  n32["过夜-张江-上科大"]
  n33["结局-张江-街头过夜"]
  n34["过夜-复旦-车内"]
  n35["↔结局-仁济-尸潮围困"]:::ext
  n36["↔理发店-店内"]:::ext
  n37["↔杨高南路立交桥"]:::ext
  n38["↔小区东门-整装待发"]:::ext
  n39["↔三林路"]:::ext
  n40["↔三林安居苑-小区内部"]:::ext
  n41["↔整理整理"]:::ext
  n42["↔小区道路"]:::ext
  n43["↔新达汇-哥哥的深夜食堂"]:::ext
  n44["↔金谊广场-2F"]:::ext
  n45["↔图书馆-大厅"]:::ext
  n46["↔start"]:::ext
  n47["↔仁济南院-检验科-内部"]:::ext
  n48["↔仁济南院-门诊药房"]:::ext
  n49["↔仁济南院-住院部走廊"]:::ext
  n50["↔建平-宿舍-内部"]:::ext
  n51["↔张江-AI岛-机房"]:::ext
  n52["↔张江-华大-动力站"]:::ext
  n53["↔张江-上科大-公寓走廊"]:::ext
  n54["↔复旦江湾-中央草坪"]:::ext
  n55["↔建平-教师小区门口"]:::ext
  n0 --> n7
  n0 -.-> n15
  n0 --> n12
  n0 --> n1
  n0 --> n3
  n0 --> n2
  n0 --> n4
  n0 -.-> n16
  n0 --> n5
  n0 -.-> n17
  n0 --> n6
  n0 --> n13
  n0 -.-> n18
  n0 --> n10
  n0 -.-> n19
  n0 --> n8
  n0 --> n20
  n0 --> n25
  n0 --> n21
  n0 --> n22
  n0 --> n23
  n0 --> n27
  n0 --> n28
  n0 --> n26
  n0 --> n29
  n0 --> n30
  n0 --> n31
  n0 --> n32
  n0 --> n33
  n0 --> n11
  n0 --> n34
  n0 --> n9
  n0 --> n24
  n13 --> n14
  classDef ext fill:#555,color:#ccc;
