flowchart LR
  n0["建平-校园门口"]
  n1["建平-崮山路-井盖"]
  n2["建平-崮山路-阀门箱"]
  n3["建平-崮山路-阀门箱-锁着"]
  n4["建平-崮山路-阀门箱-查看"]
  n5["建平-前门"]
  n6["建平-前门-清场"]
  n7["结局-前门失守"]
  n8["建平-后门"]
  n9["建平-后门-开门"]
  n10["建平-后门-手枪"]
  n11["建平-结局-空枪"]
  n12["建平-后门-斧头"]
  n13["建平-后门-斧头-胜利"]
  n14["建平-后门-匕首"]
  n15["建平-后门-匕首-胜利"]
  n16["建平-后门-开打"]
  n17["建平-后门-开打-胜利"]
  n18["结局-后门失守"]
  n19["建平-后门-内侧"]
  n20["建平-后门-内侧-暴露"]
  n21["建平-后门-内侧-开打"]
  n22["建平-后门-内侧-清场"]
  n23["建平-后门-内侧-开门"]
  n24["建平-后门-开门-清场后"]
  n25["结局-后门-自投罗网"]
  n26["建平-后门辅路"]
  n27["建平-前往复旦"]
  n28["复旦江湾"]
  n29["建平-金苹果广场"]
  n30["建平-金苹果大道"]
  n31["建平-地下车库-西口"]
  n32["建平-地下车库-大道口"]
  n33["建平-地下车库"]
  n34["建平-地下车库-消防柜"]
  n35["建平-地下车库-消防柜-取斧"]
  n36["建平-地下车库-工具间"]
  n37["建平-地下车库-工具间-开门"]
  n38["建平-地下车库-工具间-拿面具"]
  n39["建平-水池"]
  n40["建平-操场"]
  n41["建平-操场-踢球"]
  n42["建平-思贤堂"]
  n43["建平-行政楼-1F"]
  n44["建平-行政楼-2F"]
  n45["建平-行政楼-3F"]
  n46["建平-行政楼-天台"]
  n47["建平-行政楼-东楼梯"]
  n48["建平-行政楼-西楼梯"]
  n49["建平-挹芬楼北门"]
  n50["建平-挹芬楼南门"]
  n51["建平-挹芬楼-1F-西侧走廊"]
  n52["建平-挹芬楼-1F-西侧走廊-清场"]
  n53["建平-挹芬楼-1F-东侧走廊"]
  n54["建平-挹芬楼-1F-东侧走廊-清场"]
  n55["建平-挹芬楼-1F-休息区"]
  n56["结局-挹芬楼失守"]
  n57["建平-挹芬楼-2F"]
  n58["建平-挹芬楼-3F"]
  n59["建平-挹芬楼-4F"]
  n60["建平-挹芬楼-5F"]
  n61["建平-挹芬楼-6F"]
  n62["建平-挹芬楼-东楼梯"]
  n63["建平-挹芬楼-西楼梯"]
  n64["建平-挹芬楼-电梯"]
  n65["建平-致真楼-1F"]
  n66["建平-致真楼-2F"]
  n67["建平-致真楼-3F"]
  n68["建平-致真楼-4F"]
  n69["建平-致真楼-5F"]
  n70["建平-致真楼-东楼梯"]
  n71["建平-致真楼-西楼梯"]
  n72["建平-致真楼-电梯"]
  n73["建平-致真楼-1F-老吴杂物室"]
  n74["建平-致真楼-1F-老吴杂物室-翻货架"]
  n75["建平-致真楼-1F-老吴杂物室-万用表"]
  n76["建平-致真楼-1F-老吴杂物室-铁柜"]
  n77["建平-致真楼-1F-老吴杂物室-螺丝刀"]
  n78["建平-致真楼-1F-老吴杂物室-查看老吴"]
  n79["建平-致真楼-1F-老吴杂物室-搜尸体"]
  n80["建平-致真楼-1F-老吴杂物室-战斗"]
  n81["建平-致真楼-1F-老吴杂物室-击杀"]
  n82["建平-致真楼-1F-老吴杂物室-抢管线图"]
  n83["结局-被老吴咬死"]
  n84["建平-致真楼-2F-化学实验室"]
  n85["建平-致真楼-2F-化学实验室-火把"]
  n86["建平-致真楼-2F-化学实验室-没螺丝刀"]
  n87["建平-致真楼-2F-化学实验室-拆枪"]
  n88["建平-远翔楼-1F"]
  n89["建平-远翔楼-2F"]
  n90["建平-远翔楼-3F"]
  n91["建平-远翔楼-3F-物理办公室-没钥匙"]
  n92["建平-远翔楼-4F"]
  n93["建平-远翔楼-5F"]
  n94["建平-远翔楼-东楼梯"]
  n95["建平-远翔楼-西楼梯"]
  n96["建平-远翔楼-1F-医务室"]
  n97["建平-远翔楼-1F-医务室-拿药"]
  n98["建平-远翔楼-3F-物理办公室"]
  n99["建平-远翔楼-4F-高三14班"]
  n100["建平-远翔楼-4F-高三14班-窗边"]
  n101["建平-远翔楼-4F-高三14班-电脑坏"]
  n102["建平-远翔楼-4F-高三14班-修电脑"]
  n103["建平-远翔楼-4F-高三14班-galgame"]
  n104["建平-远翔楼-4F-高三14班-galgame-防波堤"]
  n105["建平-远翔楼-4F-高三14班-galgame-失落的沉默"]
  n106["建平-远翔楼-4F-高三14班-galgame-动摇的坦白"]
  n107["建平-远翔楼-4F-高三14班-galgame-尘封的真相"]
  n108["建平-远翔楼-4F-高三14班-galgame-坏结算"]
  n109["建平-远翔楼-4F-高三14班-galgame-普通结算"]
  n110["建平-远翔楼-4F-高三14班-galgame-真结算"]
  n111["建平-远翔楼-4F-高三14班-galgame-wqx存档"]
  n112["建平-远翔楼-4F-高三14班-看B站"]
  n113["建平-远翔楼-4F-高三14班-方便面"]
  n114["建平-食堂"]
  n115["建平-食堂-刘冠宇"]
  n116["建平-食堂-后厨"]
  n117["建平-食堂-后厨-找食物"]
  n118["建平-食堂-后厨-窒息"]
  n119["建平-食堂-煤气阀"]
  n120["建平-食堂-煤气阀-战斗"]
  n121["建平-食堂-煤气阀-关阀"]
  n122["结局-煤气中毒"]
  n123["建平-宿舍-门口"]
  n124["建平-宿舍-内部"]
  n125["建平-宿舍-内部-休息"]
  n126["建平-宿舍-内部-发现狼人杀手牌"]
  n127["建平-宿舍-内部-清场"]
  n128["结局-宿舍失守"]
  n129["建平-弘渊楼-1F"]
  n130["建平-弘渊楼-1F-借阅处"]
  n131["建平-弘渊楼-1F-借阅处-借书证"]
  n132["建平-弘渊楼-2F"]
  n133["建平-弘渊楼-2F-李娟"]
  n134["建平-弘渊楼-2F-李娟-清醒"]
  n135["建平-弘渊楼-2F-李娟-毒水"]
  n136["建平-弘渊楼-2F-李娟-发作"]
  n137["建平-弘渊楼-2F-李娟-转化"]
  n138["建平-弘渊楼-2F-李娟-战斗"]
  n139["建平-弘渊楼-2F-李娟-解脱"]
  n140["建平-弘渊楼-2F-李娟-抓伤"]
  n141["建平-弘渊楼-2F-保温杯-粉色"]
  n142["建平-弘渊楼-2F-保温杯-另一只"]
  n143["建平-弘渊楼-2F-保温杯-喝水"]
  n144["建平-弘渊楼-2F-保温杯-灌水"]
  n145["结局-阅览室的常客"]
  n146["建平-弘渊楼-3F"]
  n147["建平-弘渊楼-4F"]
  n148["建平-弘渊楼-楼梯"]
  n149["建平-弘渊楼-4F-电脑区"]
  n150["建平-弘渊楼-4F-电脑区-窗边"]
  n151["建平-弘渊楼-4F-电脑区-蔡镜晓"]
  n152["建平-济美楼-1F"]
  n153["建平-济美楼-2F"]
  n154["建平-济美楼-3F"]
  n155["建平-济美楼-4F"]
  n156["建平-济美楼-东楼梯"]
  n157["建平-济美楼-西楼梯"]
  n158["建平-济美楼-1F-心理教室"]
  n159["建平-济美楼-4F-音乐教室"]
  n160["建平-济美楼-4F-音乐教室-听音乐"]
  n161["建平-废弃小楼-1F"]
  n162["建平-废弃小楼-2F"]
  n163["建平-废弃小楼-3F"]
  n164["建平-廊桥-锁门"]
  n165["建平-废弃小楼-楼梯"]
  n166["建平-废弃小楼-3F-团委工作室"]
  n167["建平-废弃小楼-3F-团委工作室-内胆"]
  n168["建平-废弃小楼-3F-团委工作室-收好内胆"]
  n169["建平-Harsh堵住"]
  n170["建平-Harsh堵住-火焚"]
  n171["建平-Harsh堵住-驱赶"]
  n172["建平-Harsh堵住-逃跑"]
  n173["建平-橘猫-相遇"]
  n174["建平-橘猫-亲近"]
  n175["建平-橘猫-带路"]
  n176["建平-致真楼-3F-科创实验室"]
  n177["建平-致真楼-4F-生物实验室"]
  n178["建平-致真楼-5F-物理实验室"]
  n179["建平-致真楼-5F-物理实验室-锁柜"]
  n180["建平-致真楼-5F-物理实验室-螺丝刀"]
  n181["建平-远翔楼-1F-圆厅"]
  n182["建平-远翔楼-1F-圆厅-听琴"]
  n183["建平-远翔楼-2F-高三教室"]
  n184["建平-远翔楼-3F-高三教室"]
  n185["建平-远翔楼-4F-高三13班"]
  n186["建平-远翔楼-5F-自习室"]
  n187["建平-弘渊楼-3F-阅览区"]
  n188["建平-济美楼-1F-饮料机"]
  n189["建平-济美楼-2F-美术教室"]
  n190["建平-济美楼-3F-JTV办公室"]
  n191["建平-挹芬楼-1F-公开课教室"]
  n192["建平-挹芬楼-1F-饮料机"]
  n193["建平-挹芬楼-2F-高一教室"]
  n194["建平-挹芬楼-2F-高一教室-食品"]
  n195["建平-挹芬楼-3F-高一教室"]
  n196["建平-挹芬楼-3F-高一教室-讲台"]
  n197["建平-挹芬楼-3F-高一教室-纸条"]
  n198["建平-挹芬楼-3F-机房"]
  n199["建平-挹芬楼-4F-高二教室"]
  n200["建平-挹芬楼-4F-机房"]
  n201["建平-挹芬楼-5F-高二教室"]
  n202["建平-躲藏-挹芬楼5F高二教室"]
  n203["建平-挹芬楼-5F-高二教室-学生"]
  n204["建平-挹芬楼-5F-高二教室-救活"]
  n205["建平-挹芬楼-5F-高二教室-学生已救"]
  n206["建平-挹芬楼-5F-高二教室-学生尸体"]
  n207["建平-挹芬楼-5F-高二教室-碰尸体"]
  n208["建平-挹芬楼-5F-高二教室-黑板"]
  n209["建平-挹芬楼-6F-自习教室"]
  n210["建平-挹芬楼-6F-自习教室-窗边"]
  n211["建平-挹芬楼-6F-自习教室-食品"]
  n212["建平-挹芬楼-6F-自习教室-食品-吃掉"]
  n213["建平-挹芬楼-6F-自习教室-食品-收下"]
  n214["建平-行政楼-1F-教学处"]
  n215["建平-行政楼-2F-文印室"]
  n216["建平-行政楼-2F-文印室-手表"]
  n217["建平-行政楼-3F-公开课教室"]
  n218["建平-废弃小楼-1F-纸箱"]
  n219["建平-废弃小楼-1F-纸箱-拿枪"]
  n220["建平-废弃小楼-2F-活动室"]
  n221["建平-门卫室"]
  n222["建平-门卫室-外卖"]
  n223["建平-躲藏-14班"]
  n224["建平-躲藏-物理办公室"]
  n225["建平-躲藏-电脑区"]
  n226["建平-躲藏-挹芬楼机房3F"]
  n227["建平-躲藏-挹芬楼机房4F"]
  n228["建平-躲藏-团委工作室"]
  n229["建平-躲藏-食堂"]
  n230["建平-躲藏-天台"]
  n231["建平-躲藏-操场灌木丛"]
  n232["建平-躲藏-金苹果大道报刊亭"]
  n233["↔整理整理"]:::ext
  n234["↔罗山路立交桥下"]:::ext
  n235["↔结局-丧尸的围殴"]:::ext
  n0 --> n5
  n0 --> n8
  n0 --> n1
  n1 --> n2
  n1 --> n0
  n2 --> n4
  n2 -.-> n3
  n2 --> n1
  n3 --> n1
  n4 --> n2
  n5 --> n6
  n5 -.-> n7
  n5 -.-> n7
  n5 --> n29
  n5 --> n0
  n6 --> n29
  n8 --> n9
  n8 --> n26
  n8 --> n0
  n9 --> n16
  n9 --> n0
  n9 --> n11
  n9 --> n12
  n9 --> n14
  n10 --> n26
  n12 --> n13
  n12 -.-> n18
  n12 -.-> n18
  n13 --> n26
  n14 --> n15
  n14 -.-> n18
  n14 -.-> n18
  n15 --> n26
  n16 --> n17
  n16 -.-> n18
  n16 -.-> n18
  n17 --> n26
  n19 --> n21
  n19 --> n26
  n19 -.-> n20
  n19 --> n23
  n20 --> n26
  n21 --> n22
  n21 -.-> n25
  n21 -.-> n25
  n22 --> n23
  n22 --> n26
  n23 --> n0
  n23 --> n26
  n24 --> n26
  n26 --> n19
  n26 --> n114
  n26 --> n88
  n26 --> n65
  n26 --> n173
  n26 --> n8
  n27 --> n28
  n29 --> n5
  n29 --> n43
  n29 --> n49
  n29 --> n65
  n29 --> n30
  n29 --> n31
  n29 --> n221
  n30 --> n29
  n30 --> n88
  n30 --> n114
  n30 --> n152
  n30 --> n32
  n30 --> n173
  n30 --> n232
  n31 --> n33
  n31 --> n29
  n32 --> n33
  n32 --> n30
  n33 --> n36
  n33 --> n31
  n33 --> n32
  n34 --> n35
  n34 --> n33
  n35 --> n33
  n36 --> n33
  n36 --> n37
  n37 --> n36
  n38 --> n36
  n39 --> n161
  n39 --> n50
  n39 --> n129
  n39 --> n152
  n40 --> n114
  n40 --> n129
  n40 --> n123
  n40 --> n41
  n40 --> n173
  n40 --> n231
  n41 --> n40
  n42 --> n50
  n42 --> n161
  n43 --> n29
  n43 --> n47
  n43 --> n48
  n43 --> n214
  n44 --> n47
  n44 --> n48
  n44 --> n215
  n45 --> n47
  n45 --> n48
  n45 --> n46
  n45 --> n217
  n46 --> n230
  n46 --> n45
  n47 --> n43
  n47 --> n44
  n47 --> n45
  n48 --> n43
  n48 --> n44
  n48 --> n45
  n49 --> n29
  n49 --> n51
  n50 --> n39
  n50 --> n42
  n50 --> n53
  n51 --> n52
  n51 -.-> n56
  n51 -.-> n56
  n51 --> n49
  n51 --> n63
  n51 --> n64
  n51 --> n191
  n51 --> n53
  n52 --> n51
  n53 --> n54
  n53 -.-> n56
  n53 -.-> n56
  n53 --> n50
  n53 --> n62
  n53 --> n55
  n53 --> n51
  n54 --> n53
  n55 --> n192
  n55 --> n53
  n57 --> n62
  n57 --> n63
  n57 --> n64
  n57 --> n193
  n57 --> n173
  n58 --> n62
  n58 --> n63
  n58 --> n64
  n58 --> n195
  n58 --> n198
  n59 --> n62
  n59 --> n63
  n59 --> n64
  n59 --> n199
  n59 --> n200
  n60 --> n62
  n60 --> n63
  n60 --> n64
  n60 --> n201
  n61 --> n62
  n61 --> n63
  n61 --> n64
  n61 --> n209
  n62 --> n53
  n62 --> n57
  n62 --> n58
  n62 --> n59
  n62 --> n60
  n62 --> n61
  n63 --> n51
  n63 --> n57
  n63 --> n58
  n63 --> n59
  n63 --> n60
  n63 --> n61
  n64 --> n51
  n64 --> n57
  n64 --> n58
  n64 --> n59
  n64 --> n60
  n64 --> n61
  n65 --> n29
  n65 --> n26
  n65 --> n70
  n65 --> n71
  n65 --> n72
  n65 --> n73
  n66 --> n70
  n66 --> n71
  n66 --> n72
  n66 --> n84
  n67 --> n70
  n67 --> n71
  n67 --> n72
  n67 --> n90
  n67 --> n176
  n68 --> n70
  n68 --> n71
  n68 --> n72
  n68 --> n92
  n68 --> n177
  n69 --> n70
  n69 --> n71
  n69 --> n72
  n69 --> n93
  n69 --> n178
  n70 --> n70
  n70 --> n65
  n70 --> n66
  n70 --> n67
  n70 --> n68
  n70 --> n69
  n71 --> n65
  n71 --> n66
  n71 --> n67
  n71 --> n68
  n71 --> n69
  n72 --> n65
  n72 --> n66
  n72 --> n67
  n72 --> n68
  n72 --> n69
  n73 --> n74
  n73 --> n78
  n73 --> n76
  n73 --> n65
  n74 --> n75
  n74 --> n73
  n75 --> n73
  n76 --> n73
  n77 --> n73
  n78 --> n79
  n78 --> n73
  n79 --> n73
  n80 --> n81
  n80 -.-> n83
  n80 -.-> n83
  n81 --> n73
  n82 --> n65
  n84 --> n66
  n85 --> n84
  n86 --> n84
  n87 --> n84
  n88 --> n30
  n88 --> n26
  n88 --> n94
  n88 --> n95
  n88 --> n96
  n88 --> n181
  n88 --> n173
  n89 --> n94
  n89 --> n95
  n89 --> n183
  n90 --> n94
  n90 --> n95
  n90 --> n98
  n90 -.-> n91
  n90 --> n184
  n90 --> n67
  n91 --> n90
  n92 --> n94
  n92 --> n95
  n92 --> n99
  n92 --> n185
  n92 --> n68
  n93 --> n94
  n93 --> n95
  n93 --> n69
  n93 --> n186
  n94 --> n88
  n94 --> n89
  n94 --> n90
  n94 --> n92
  n94 --> n93
  n95 --> n95
  n95 --> n88
  n95 --> n89
  n95 --> n90
  n95 --> n92
  n95 --> n93
  n96 --> n97
  n96 --> n88
  n97 --> n96
  n98 --> n224
  n98 --> n90
  n99 --> n101
  n99 --> n100
  n99 --> n92
  n99 --> n103
  n99 --> n223
  n100 --> n99
  n101 --> n99
  n102 --> n99
  n103 --> n104
  n103 --> n99
  n104 --> n105
  n104 --> n106
  n104 --> n107
  n105 --> n108
  n105 --> n109
  n106 --> n109
  n106 --> n110
  n107 --> n109
  n107 --> n110
  n108 --> n104
  n108 --> n112
  n108 --> n99
  n109 --> n112
  n109 --> n99
  n110 --> n111
  n111 --> n112
  n111 --> n99
  n112 --> n99
  n113 --> n99
  n114 --> n30
  n114 --> n26
  n114 --> n40
  n114 --> n123
  n114 --> n116
  n114 --> n115
  n114 --> n229
  n115 --> n114
  n116 --> n117
  n116 --> n114
  n117 --> n116
  n118 --> n114
  n119 --> n120
  n119 --> n116
  n120 --> n121
  n120 -.-> n122
  n120 -.-> n122
  n121 --> n116
  n123 --> n124
  n123 --> n40
  n123 --> n114
  n124 --> n127
  n124 -.-> n128
  n124 -.-> n128
  n124 --> n125
  n124 --> n123
  n125 --> n124
  n125 --> n126
  n126 --> n124
  n127 --> n124
  n129 --> n39
  n129 --> n40
  n129 --> n130
  n129 --> n148
  n130 --> n131
  n130 --> n129
  n131 --> n130
  n132 --> n133
  n132 --> n143
  n132 --> n144
  n132 --> n148
  n133 --> n134
  n133 --> n135
  n133 --> n137
  n133 --> n136
  n133 --> n133
  n133 --> n132
  n134 --> n132
  n135 --> n132
  n136 --> n132
  n137 --> n138
  n138 --> n139
  n138 -.-> n145
  n138 -.-> n145
  n139 --> n132
  n140 --> n132
  n141 --> n132
  n142 --> n132
  n143 --> n132
  n144 --> n132
  n146 --> n148
  n146 --> n163
  n146 -.-> n164
  n146 --> n187
  n147 --> n148
  n147 --> n149
  n148 --> n129
  n148 --> n132
  n148 --> n146
  n148 --> n147
  n149 --> n151
  n149 --> n150
  n149 --> n147
  n149 --> n225
  n150 --> n150
  n150 --> n149
  n151 --> n149
  n152 --> n30
  n152 --> n39
  n152 --> n156
  n152 --> n157
  n152 --> n158
  n152 --> n188
  n153 --> n156
  n153 --> n157
  n153 --> n189
  n154 --> n156
  n154 --> n157
  n154 --> n190
  n155 --> n156
  n155 --> n157
  n155 --> n159
  n156 --> n152
  n156 --> n153
  n156 --> n154
  n156 --> n155
  n157 --> n152
  n157 --> n153
  n157 --> n154
  n157 --> n155
  n158 --> n152
  n159 --> n160
  n159 --> n155
  n160 --> n160
  n160 --> n159
  n161 --> n39
  n161 --> n42
  n161 --> n165
  n161 --> n218
  n162 --> n165
  n162 --> n220
  n163 --> n165
  n163 --> n146
  n163 -.-> n164
  n163 --> n166
  n164 --> n164
  n165 --> n161
  n165 --> n162
  n165 --> n163
  n166 --> n167
  n166 --> n228
  n166 --> n163
  n167 --> n166
  n167 --> n168
  n168 --> n166
  n169 --> n172
  n169 --> n170
  n170 --> n30
  n171 --> n30
  n172 --> n30
  n173 --> n30
  n173 --> n174
  n174 --> n175
  n174 --> n30
  n175 --> n65
  n176 --> n67
  n177 --> n68
  n178 --> n179
  n178 --> n69
  n179 --> n178
  n180 --> n178
  n181 --> n182
  n181 --> n88
  n182 --> n181
  n183 --> n89
  n184 --> n90
  n185 --> n92
  n186 --> n93
  n187 --> n146
  n188 --> n152
  n189 --> n153
  n190 --> n154
  n191 --> n51
  n192 --> n55
  n193 --> n194
  n193 --> n57
  n194 --> n193
  n195 --> n197
  n195 --> n58
  n196 --> n195
  n197 --> n195
  n198 --> n226
  n198 --> n58
  n199 --> n59
  n200 --> n227
  n200 --> n59
  n201 --> n208
  n201 --> n203
  n201 --> n60
  n201 --> n205
  n201 --> n202
  n202 --> n202
  n203 --> n201
  n203 --> n204
  n204 --> n201
  n205 --> n201
  n206 --> n207
  n206 --> n201
  n207 --> n201
  n208 --> n201
  n209 --> n211
  n209 --> n210
  n209 --> n61
  n209 --> n212
  n210 --> n209
  n211 --> n212
  n211 --> n213
  n212 --> n209
  n213 --> n209
  n214 --> n43
  n215 --> n216
  n215 --> n44
  n216 --> n215
  n217 --> n45
  n218 --> n219
  n218 --> n161
  n219 --> n218
  n220 --> n162
  n221 --> n222
  n221 --> n0
  n222 --> n0
  n223 --> n223
  n224 --> n224
  n225 --> n225
  n226 --> n226
  n227 --> n227
  n228 --> n228
  n229 --> n229
  n230 --> n230
  n231 --> n231
  n232 --> n232
  classDef ext fill:#555,color:#ccc;
