flowchart LR
  n0["张江-落地坡道"]
  n1["张江-人工智能岛闸机外"]
  n2["张江-华科路"]
  n3["张江-华科路-配送车"]
  n4["张江-街角"]
  n5["张江-街角-电车"]
  n6["张江-科苑路"]
  n7["张江-加油站"]
  n8["张江-加油站-便利店"]
  n9["张江-加油站-棚子"]
  n10["张江-加油站-棚子-战斗"]
  n11["张江-加油站-棚子-胜利"]
  n12["张江-加油站-拎桶"]
  n13["结局-张江-加油站"]
  n14["张江-AI岛-园区内"]
  n15["张江-AI岛-公司前台"]
  n16["张江-AI岛-机房"]
  n17["张江-AI岛-机房-重逢"]
  n18["张江-AI岛-机房-长谈给卡"]
  n19["张江-AI岛-机房-话题"]
  n20["张江-AI岛-机房-话题-近况"]
  n21["张江-AI岛-机房-话题-华大规矩"]
  n22["张江-AI岛-机房-话题-北岸"]
  n23["张江-AI岛-机房-话题-洪金宝"]
  n24["张江-AI岛-机房-监控"]
  n25["张江-AI岛-机房-曹睿泽"]
  n26["张江-AI岛-机房-读报告"]
  n27["张江-AI岛-机房-休息"]
  n28["张江-AI岛-食堂"]
  n29["张江-AI岛-停车场"]
  n30["张江-上科大-校门"]
  n31["张江-上科大-研究生公寓"]
  n32["张江-上科大-公寓走廊"]
  n33["张江-上科大-走廊-别的门"]
  n34["张江-上科大-曹睿泽宿舍"]
  n35["张江-上科大-宿舍-合照"]
  n36["张江-上科大-宿舍-搜刮"]
  n37["张江-上科大-教学楼门厅"]
  n38["张江-上科大-食堂"]
  n39["张江-上科大-食堂-后厨"]
  n40["张江-上科大-食堂-后厨-战斗"]
  n41["张江-上科大-食堂-后厨-胜利"]
  n42["结局-张江-上科大食堂"]
  n43["张江-华大-大门"]
  n44["张江-华大-大门-吃闭门羹"]
  n45["张江-华大-厂区广场"]
  n46["张江-华大-广场-人影"]
  n47["张江-华大-广场-近路"]
  n48["张江-华大-广场-近路-胜"]
  n49["结局-张江-厂区广场"]
  n50["张江-华大-保安亭"]
  n51["张江-华大-连廊"]
  n52["张江-华大-连廊-规程"]
  n53["张江-华大-连廊-遭遇"]
  n54["张江-华大-连廊-遭遇-胜"]
  n55["结局-张江-连廊"]
  n56["张江-华大-办公区"]
  n57["张江-华大-办公区-工位"]
  n58["张江-华大-灰区"]
  n59["张江-华大-灰区-更衣柜"]
  n60["张江-华大-灰区-穿无尘服"]
  n61["张江-华大-灰区-脱无尘服"]
  n62["张江-华大-灰区-风淋复位"]
  n63["张江-华大-风淋舱"]
  n64["张江-华大-风淋舱-关门"]
  n65["张江-华大-风淋舱-开门"]
  n66["张江-华大-风淋舱-强启失败"]
  n67["张江-华大-风淋舱-吹风"]
  n68["张江-华大-风淋舱-倒计时"]
  n69["张江-华大-风淋舱-完成"]
  n70["张江-华大-风淋舱-击退"]
  n71["张江-华大-风淋舱-泄漏"]
  n72["张江-华大-风淋舱-泄漏-乱拍"]
  n73["张江-华大-风淋舱-泄漏-复位"]
  n74["张江-华大-风淋舱-泄漏-喊"]
  n75["张江-华大-风淋舱-泄漏-解除"]
  n76["结局-张江-风淋舱"]
  n77["张江-华大-洁净主走廊"]
  n78["张江-华大-白区"]
  n79["张江-华大-白区-围攻"]
  n80["张江-华大-白区-围攻-胜"]
  n81["结局-张江-白区"]
  n82["张江-华大-白区-工位A"]
  n83["张江-华大-白区-工位A-观察"]
  n84["张江-华大-白区-工位A-试探"]
  n85["张江-华大-白区-工位战A"]
  n86["张江-华大-白区-工位战A-胜"]
  n87["张江-华大-白区-工位B"]
  n88["张江-华大-白区-工位B-观察"]
  n89["张江-华大-白区-工位B-对话"]
  n90["张江-华大-白区-工位B-误杀"]
  n91["张江-华大-白区-工位C"]
  n92["张江-华大-白区-工位C-观察"]
  n93["张江-华大-白区-工位C-试探"]
  n94["张江-华大-白区-工位战C"]
  n95["张江-华大-白区-工位战C-胜"]
  n96["结局-张江-毒气"]
  n97["张江-华大-运维区"]
  n98["张江-华大-运维区-虚惊"]
  n99["张江-华大-运维区-遭遇战"]
  n100["张江-华大-运维区-制服"]
  n101["张江-华大-运维区-闲聊"]
  n102["结局-张江-运维区"]
  n103["张江-华大-设备密室"]
  n104["张江-华大-夹层-入口"]
  n105["张江-华大-夹层-摸黑"]
  n106["张江-华大-夹层"]
  n107["张江-华大-夹层-俯瞰"]
  n108["结局-张江-夹层"]
  n109["张江-华大-动力站-初遇"]
  n110["张江-华大-动力站-会面"]
  n111["张江-华大-动力站-含糊"]
  n112["张江-华大-动力站-来历"]
  n113["张江-华大-动力站-委托"]
  n114["张江-华大-动力站-拷问"]
  n115["张江-华大-动力站-告知"]
  n116["张江-华大-动力站-谎言"]
  n117["张江-华大-动力站-沉默"]
  n118["张江-华大-动力站"]
  n119["张江-华大-动力站-聊天"]
  n120["张江-华大-动力站-聊天-自己"]
  n121["张江-华大-动力站-聊天-厂里"]
  n122["张江-华大-动力站-曹睿泽-委托"]
  n123["张江-华大-动力站-曹睿泽-回报"]
  n124["张江-华大-动力站-合照"]
  n125["张江-华大-动力站-报告"]
  n126["张江-华大-动力站-补救"]
  n127["张江-华大-动力站-柴油-接"]
  n128["张江-华大-动力站-柴油-交"]
  n129["张江-华大-动力站-纯水"]
  n130["张江-华大-动力站-灌水"]
  n131["张江-华大-动力站-取样瓶"]
  n132["张江-华大-动力站-休息"]
  n133["张江-华大-动力站-字条"]
  n134["张江-滨河绿道"]
  n135["张江-厂界便道"]
  n136["张江-川杨河南岸堤"]
  n137["张江-川杨河南岸堤-探引桥"]
  n138["张江-川杨河大桥-1"]
  n139["张江-川杨河大桥-1-胜"]
  n140["张江-川杨河大桥-2"]
  n141["张江-川杨河大桥-2-胜"]
  n142["张江-川杨河大桥-3"]
  n143["张江-川杨河大桥-3-胜"]
  n144["结局-张江-川杨河"]
  n145["张江-北岸落地"]
  n146["张江-河北岸-街口"]
  n147["张江-河北岸-沿街铺面"]
  n148["张江-检测中心-大门"]
  n149["张江-检测中心-卸货区"]
  n150["张江-检测中心-大厅"]
  n151["张江-检测中心-台账"]
  n152["张江-检测中心-走廊"]
  n153["张江-检测中心-瞎摸"]
  n154["张江-检测中心-瞎摸-胜"]
  n155["张江-检测中心-三室外"]
  n156["张江-检测中心-三室外-窥视"]
  n157["张江-检测中心-三室内"]
  n158["张江-检测中心-摔柜门"]
  n159["张江-检测中心-检测员战"]
  n160["张江-检测中心-制服"]
  n161["张江-检测中心-撤离遭遇"]
  n162["张江-检测中心-撤离-胜"]
  n163["张江-检测中心-抄录"]
  n164["结局-张江-检测中心"]
  n165["↔北蔡镇罗山立交桥"]:::ext
  n166["↔整理整理"]:::ext
  n167["↔张江立交桥"]:::ext
  n0 -.-> n1
  n1 --> n14
  n1 --> n2
  n1 --> n4
  n1 --> n134
  n2 --> n3
  n2 --> n43
  n2 --> n1
  n3 --> n2
  n4 --> n5
  n4 --> n7
  n4 --> n6
  n4 --> n1
  n5 --> n4
  n6 --> n30
  n6 --> n4
  n7 --> n8
  n7 --> n9
  n7 --> n4
  n8 --> n7
  n9 --> n10
  n9 --> n7
  n9 --> n12
  n10 --> n11
  n10 -.-> n13
  n10 -.-> n13
  n11 --> n9
  n12 --> n7
  n14 --> n15
  n14 --> n28
  n14 --> n29
  n14 --> n1
  n15 --> n16
  n15 --> n14
  n16 --> n17
  n16 --> n19
  n16 --> n24
  n16 --> n27
  n16 --> n15
  n17 --> n18
  n18 --> n16
  n19 --> n20
  n19 --> n21
  n19 --> n22
  n19 --> n23
  n19 --> n16
  n20 --> n19
  n21 --> n19
  n22 --> n19
  n23 --> n19
  n24 --> n16
  n25 --> n16
  n26 --> n16
  n27 --> n27
  n27 --> n16
  n28 --> n14
  n29 --> n14
  n30 --> n31
  n30 --> n37
  n30 --> n6
  n31 --> n32
  n31 --> n38
  n31 --> n30
  n32 --> n34
  n32 --> n33
  n32 --> n31
  n33 --> n32
  n33 --> n31
  n34 --> n35
  n34 --> n36
  n34 --> n32
  n35 --> n34
  n36 --> n34
  n37 --> n30
  n38 --> n39
  n38 --> n31
  n39 --> n40
  n39 --> n38
  n39 --> n39
  n40 --> n41
  n40 -.-> n42
  n40 -.-> n42
  n41 --> n39
  n43 --> n45
  n43 --> n44
  n43 --> n2
  n44 --> n43
  n45 --> n46
  n45 --> n50
  n45 --> n43
  n46 --> n45
  n47 --> n48
  n47 -.-> n49
  n47 -.-> n49
  n48 --> n50
  n48 --> n45
  n50 --> n51
  n50 --> n45
  n51 --> n52
  n51 --> n58
  n51 --> n56
  n51 --> n50
  n52 --> n51
  n53 --> n54
  n53 -.-> n55
  n53 -.-> n55
  n54 --> n51
  n56 --> n57
  n56 --> n51
  n57 --> n56
  n58 --> n63
  n58 --> n59
  n58 --> n104
  n58 --> n51
  n58 --> n62
  n59 --> n60
  n59 --> n61
  n59 --> n58
  n60 --> n58
  n61 --> n58
  n62 --> n58
  n63 --> n64
  n63 --> n66
  n63 --> n58
  n63 --> n69
  n64 --> n63
  n65 --> n63
  n66 --> n63
  n67 --> n68
  n67 --> n70
  n67 --> n71
  n68 --> n69
  n69 --> n77
  n70 --> n58
  n70 -.-> n76
  n71 --> n72
  n71 --> n74
  n71 --> n73
  n72 --> n71
  n72 --> n75
  n73 --> n75
  n74 --> n71
  n75 --> n58
  n77 --> n78
  n77 --> n97
  n77 --> n63
  n78 --> n79
  n78 --> n77
  n78 --> n82
  n78 --> n87
  n78 --> n91
  n78 --> n118
  n79 --> n80
  n79 -.-> n81
  n79 -.-> n81
  n80 --> n77
  n82 --> n83
  n82 --> n84
  n82 --> n85
  n82 --> n78
  n83 --> n82
  n84 --> n85
  n84 --> n78
  n85 --> n86
  n85 -.-> n81
  n85 -.-> n81
  n86 --> n78
  n87 --> n88
  n87 --> n89
  n87 --> n90
  n87 --> n78
  n88 --> n87
  n89 --> n78
  n90 --> n78
  n91 --> n92
  n91 --> n93
  n91 --> n94
  n91 --> n78
  n92 --> n91
  n93 --> n94
  n93 --> n78
  n94 --> n95
  n94 -.-> n96
  n94 -.-> n96
  n95 --> n78
  n97 --> n98
  n97 --> n103
  n97 --> n77
  n97 --> n99
  n98 --> n109
  n98 --> n97
  n99 --> n100
  n99 -.-> n102
  n99 -.-> n102
  n100 --> n97
  n101 --> n109
  n101 --> n97
  n103 --> n97
  n104 --> n105
  n104 --> n58
  n104 --> n106
  n104 --> n108
  n105 --> n58
  n106 --> n107
  n106 --> n109
  n106 --> n58
  n107 --> n106
  n109 --> n110
  n109 --> n118
  n110 --> n112
  n110 --> n111
  n111 --> n118
  n112 --> n113
  n112 --> n114
  n113 --> n118
  n113 --> n123
  n114 --> n115
  n114 --> n116
  n114 --> n117
  n115 --> n118
  n116 --> n118
  n117 --> n118
  n118 --> n119
  n118 --> n129
  n118 --> n132
  n118 --> n78
  n118 --> n106
  n118 --> n135
  n119 --> n120
  n119 --> n121
  n119 --> n122
  n119 --> n118
  n119 --> n114
  n120 --> n119
  n121 --> n119
  n122 --> n119
  n122 --> n123
  n123 --> n118
  n124 --> n119
  n125 --> n119
  n126 --> n118
  n127 --> n118
  n128 --> n118
  n129 --> n129
  n129 --> n131
  n129 --> n118
  n129 --> n130
  n130 --> n118
  n131 --> n118
  n132 --> n132
  n132 --> n118
  n133 --> n118
  n134 --> n136
  n134 --> n135
  n134 --> n1
  n135 --> n134
  n135 --> n118
  n136 --> n138
  n136 --> n137
  n136 --> n144
  n136 --> n134
  n137 --> n136
  n138 --> n139
  n138 -.-> n144
  n138 -.-> n144
  n139 --> n140
  n140 --> n141
  n140 -.-> n144
  n140 -.-> n144
  n141 --> n142
  n142 --> n143
  n142 -.-> n144
  n142 -.-> n144
  n143 --> n146
  n145 -.-> n146
  n146 --> n148
  n146 --> n147
  n146 --> n138
  n147 --> n146
  n148 --> n150
  n148 --> n149
  n148 --> n146
  n149 --> n152
  n149 --> n148
  n150 --> n151
  n150 --> n152
  n150 --> n148
  n151 --> n152
  n151 --> n150
  n152 --> n153
  n152 --> n150
  n152 --> n149
  n152 --> n155
  n153 --> n154
  n153 -.-> n164
  n153 -.-> n164
  n154 --> n155
  n154 --> n152
  n155 --> n157
  n155 --> n152
  n155 --> n156
  n156 --> n155
  n157 --> n158
  n157 --> n159
  n157 --> n152
  n158 --> n159
  n159 --> n160
  n159 -.-> n164
  n159 -.-> n164
  n160 --> n152
  n161 --> n162
  n161 -.-> n164
  n161 -.-> n164
  n162 --> n150
  n163 --> n150
  classDef ext fill:#555,color:#ccc;
