flowchart LR
  n0["张江-落地坡道"]
  n1["张江-人工智能岛闸机外"]
  n2["张江-AI岛-水景"]
  n3["张江-华科路"]
  n4["张江-华科路-配送车"]
  n5["张江-街角"]
  n6["张江-街角-电车"]
  n7["张江-科苑路"]
  n8["张江-加油站"]
  n9["张江-加油站-便利店"]
  n10["张江-加油站-棚子"]
  n11["张江-加油站-棚子-战斗"]
  n12["张江-加油站-棚子-胜利"]
  n13["张江-加油站-拎桶"]
  n14["结局-张江-加油站"]
  n15["张江-AI岛-园区内"]
  n16["张江-AI岛-公司前台"]
  n17["张江-AI岛-机房"]
  n18["张江-AI岛-机房-重逢"]
  n19["张江-AI岛-机房-长谈给卡"]
  n20["张江-AI岛-机房-话题"]
  n21["张江-AI岛-机房-话题-近况"]
  n22["张江-AI岛-机房-话题-华大规矩"]
  n23["张江-AI岛-机房-话题-北岸"]
  n24["张江-AI岛-机房-话题-洪金宝"]
  n25["张江-AI岛-机房-监控"]
  n26["张江-AI岛-机房-曹睿泽"]
  n27["张江-AI岛-机房-读报告"]
  n28["张江-AI岛-机房-休息"]
  n29["张江-AI岛-食堂"]
  n30["张江-AI岛-停车场"]
  n31["张江-上科大-校门"]
  n32["张江-上科大-研究生公寓"]
  n33["张江-上科大-公寓走廊"]
  n34["张江-上科大-走廊-别的门"]
  n35["张江-上科大-曹睿泽宿舍"]
  n36["张江-上科大-宿舍-合照"]
  n37["张江-上科大-宿舍-搜刮"]
  n38["张江-上科大-教学楼门厅"]
  n39["张江-上科大-食堂"]
  n40["张江-上科大-食堂-后厨"]
  n41["张江-上科大-食堂-后厨-战斗"]
  n42["张江-上科大-食堂-后厨-胜利"]
  n43["结局-张江-上科大食堂"]
  n44["张江-华大-大门"]
  n45["张江-华大-大门-吃闭门羹"]
  n46["张江-华大-厂区广场"]
  n47["张江-华大-广场-人影"]
  n48["张江-华大-广场-近路"]
  n49["张江-华大-广场-近路-胜"]
  n50["结局-张江-厂区广场"]
  n51["张江-华大-保安亭"]
  n52["张江-华大-连廊"]
  n53["张江-华大-连廊-规程"]
  n54["张江-华大-连廊-遭遇"]
  n55["张江-华大-连廊-遭遇-胜"]
  n56["结局-张江-连廊"]
  n57["张江-华大-办公区"]
  n58["张江-华大-办公区-工位"]
  n59["张江-华大-灰区"]
  n60["张江-华大-灰区-更衣柜"]
  n61["张江-华大-灰区-穿无尘服"]
  n62["张江-华大-灰区-脱无尘服"]
  n63["张江-华大-灰区-风淋复位"]
  n64["张江-华大-风淋舱"]
  n65["张江-华大-风淋舱-关门"]
  n66["张江-华大-风淋舱-开门"]
  n67["张江-华大-风淋舱-强启失败"]
  n68["张江-华大-风淋舱-吹风"]
  n69["张江-华大-风淋舱-倒计时"]
  n70["张江-华大-风淋舱-完成"]
  n71["张江-华大-风淋舱-击退"]
  n72["张江-华大-风淋舱-泄漏"]
  n73["张江-华大-风淋舱-泄漏-乱拍"]
  n74["张江-华大-风淋舱-泄漏-复位"]
  n75["张江-华大-风淋舱-泄漏-喊"]
  n76["张江-华大-风淋舱-泄漏-解除"]
  n77["结局-张江-风淋舱"]
  n78["张江-华大-洁净主走廊"]
  n79["张江-华大-白区"]
  n80["张江-华大-白区-围攻"]
  n81["张江-华大-白区-围攻-胜"]
  n82["结局-张江-白区"]
  n83["张江-华大-白区-工位A"]
  n84["张江-华大-白区-工位A-观察"]
  n85["张江-华大-白区-工位A-试探"]
  n86["张江-华大-白区-工位战A"]
  n87["张江-华大-白区-工位战A-胜"]
  n88["张江-华大-白区-工位B"]
  n89["张江-华大-白区-工位B-观察"]
  n90["张江-华大-白区-工位B-对话"]
  n91["张江-华大-白区-工位B-误杀"]
  n92["张江-华大-白区-工位C"]
  n93["张江-华大-白区-工位C-观察"]
  n94["张江-华大-白区-工位C-试探"]
  n95["张江-华大-白区-工位战C"]
  n96["张江-华大-白区-工位战C-胜"]
  n97["结局-张江-毒气"]
  n98["张江-华大-运维区"]
  n99["张江-华大-运维区-虚惊"]
  n100["张江-华大-运维区-遭遇战"]
  n101["张江-华大-运维区-制服"]
  n102["张江-华大-运维区-闲聊"]
  n103["结局-张江-运维区"]
  n104["张江-华大-设备密室"]
  n105["张江-华大-夹层-入口"]
  n106["张江-华大-夹层-摸黑"]
  n107["张江-华大-夹层"]
  n108["张江-华大-夹层-俯瞰"]
  n109["结局-张江-夹层"]
  n110["张江-华大-动力站-初遇"]
  n111["张江-华大-动力站-会面"]
  n112["张江-华大-动力站-含糊"]
  n113["张江-华大-动力站-来历"]
  n114["张江-华大-动力站-委托"]
  n115["张江-华大-动力站-拷问"]
  n116["张江-华大-动力站-告知"]
  n117["张江-华大-动力站-谎言"]
  n118["张江-华大-动力站-沉默"]
  n119["张江-华大-动力站"]
  n120["张江-华大-动力站-聊天"]
  n121["张江-华大-动力站-聊天-自己"]
  n122["张江-华大-动力站-聊天-厂里"]
  n123["张江-华大-动力站-曹睿泽-委托"]
  n124["张江-华大-动力站-曹睿泽-回报"]
  n125["张江-华大-动力站-合照"]
  n126["张江-华大-动力站-报告"]
  n127["张江-华大-动力站-补救"]
  n128["张江-华大-动力站-柴油-接"]
  n129["张江-华大-动力站-柴油-交"]
  n130["张江-华大-动力站-纯水"]
  n131["张江-华大-动力站-灌水"]
  n132["张江-华大-动力站-取样瓶"]
  n133["张江-华大-动力站-休息"]
  n134["张江-华大-动力站-字条"]
  n135["张江-滨河绿道"]
  n136["张江-厂界便道"]
  n137["张江-川杨河南岸堤"]
  n138["张江-川杨河南岸堤-探引桥"]
  n139["张江-川杨河大桥-1"]
  n140["张江-川杨河大桥-1-胜"]
  n141["张江-川杨河大桥-2"]
  n142["张江-川杨河大桥-2-胜"]
  n143["张江-川杨河大桥-3"]
  n144["张江-川杨河大桥-3-胜"]
  n145["结局-张江-川杨河"]
  n146["张江-北岸落地"]
  n147["张江-河北岸-街口"]
  n148["张江-河北岸-沿街铺面"]
  n149["张江-检测中心-大门"]
  n150["张江-检测中心-卸货区"]
  n151["张江-检测中心-大厅"]
  n152["张江-检测中心-台账"]
  n153["张江-检测中心-走廊"]
  n154["张江-检测中心-瞎摸"]
  n155["张江-检测中心-瞎摸-胜"]
  n156["张江-检测中心-三室外"]
  n157["张江-检测中心-三室外-窥视"]
  n158["张江-检测中心-三室内"]
  n159["张江-检测中心-摔柜门"]
  n160["张江-检测中心-检测员战"]
  n161["张江-检测中心-制服"]
  n162["张江-检测中心-撤离遭遇"]
  n163["张江-检测中心-撤离-胜"]
  n164["张江-检测中心-抄录"]
  n165["结局-张江-检测中心"]
  n166["↔北蔡镇罗山立交桥"]:::ext
  n167["↔整理整理"]:::ext
  n168["↔张江立交桥"]:::ext
  n0 -.-> n1
  n1 --> n15
  n1 --> n3
  n1 --> n5
  n1 --> n135
  n1 --> n2
  n2 --> n1
  n3 --> n4
  n3 --> n44
  n3 --> n1
  n4 --> n3
  n5 --> n6
  n5 --> n8
  n5 --> n7
  n5 --> n1
  n6 --> n5
  n7 --> n31
  n7 --> n5
  n8 --> n9
  n8 --> n10
  n8 --> n5
  n9 --> n8
  n10 --> n11
  n10 --> n8
  n10 --> n13
  n11 --> n12
  n11 -.-> n14
  n11 -.-> n14
  n12 --> n10
  n13 --> n8
  n15 --> n16
  n15 --> n29
  n15 --> n30
  n15 --> n1
  n16 --> n17
  n16 --> n15
  n17 --> n18
  n17 --> n20
  n17 --> n25
  n17 --> n28
  n17 --> n16
  n18 --> n19
  n19 --> n17
  n20 --> n21
  n20 --> n22
  n20 --> n23
  n20 --> n24
  n20 --> n17
  n21 --> n20
  n22 --> n20
  n23 --> n20
  n24 --> n20
  n25 --> n17
  n26 --> n17
  n27 --> n17
  n28 --> n28
  n28 --> n17
  n29 --> n15
  n30 --> n15
  n31 --> n32
  n31 --> n38
  n31 --> n7
  n32 --> n33
  n32 --> n39
  n32 --> n31
  n33 --> n35
  n33 --> n34
  n33 --> n32
  n34 --> n33
  n34 --> n32
  n35 --> n36
  n35 --> n37
  n35 --> n33
  n36 --> n35
  n37 --> n35
  n38 --> n31
  n39 --> n40
  n39 --> n32
  n40 --> n41
  n40 --> n39
  n40 --> n40
  n41 --> n42
  n41 -.-> n43
  n41 -.-> n43
  n42 --> n40
  n44 --> n46
  n44 --> n45
  n44 --> n3
  n45 --> n44
  n46 --> n47
  n46 --> n51
  n46 --> n44
  n46 --> n48
  n47 --> n46
  n48 --> n49
  n48 -.-> n50
  n48 -.-> n50
  n49 --> n51
  n49 --> n46
  n51 --> n52
  n51 --> n46
  n52 --> n53
  n52 --> n59
  n52 --> n57
  n52 --> n51
  n52 --> n54
  n53 --> n52
  n54 --> n55
  n54 -.-> n56
  n54 -.-> n56
  n55 --> n52
  n57 --> n58
  n57 --> n52
  n58 --> n57
  n59 --> n64
  n59 --> n60
  n59 --> n105
  n59 --> n52
  n59 --> n63
  n60 --> n61
  n60 --> n62
  n60 --> n59
  n61 --> n59
  n62 --> n59
  n63 --> n59
  n64 --> n65
  n64 --> n67
  n64 --> n59
  n64 --> n70
  n65 --> n64
  n66 --> n64
  n67 --> n64
  n68 --> n69
  n68 --> n71
  n68 --> n72
  n69 --> n70
  n70 --> n78
  n71 --> n59
  n71 -.-> n77
  n72 --> n73
  n72 --> n75
  n72 --> n74
  n73 --> n72
  n73 --> n76
  n74 --> n76
  n75 --> n72
  n76 --> n59
  n78 --> n79
  n78 --> n98
  n78 --> n64
  n79 --> n80
  n79 --> n78
  n79 --> n83
  n79 --> n88
  n79 --> n92
  n79 --> n119
  n80 --> n81
  n80 -.-> n82
  n80 -.-> n82
  n81 --> n78
  n83 --> n84
  n83 --> n85
  n83 --> n86
  n83 --> n79
  n84 --> n83
  n85 --> n86
  n85 --> n79
  n86 --> n87
  n86 -.-> n82
  n86 -.-> n82
  n87 --> n79
  n88 --> n89
  n88 --> n90
  n88 --> n91
  n88 --> n79
  n89 --> n88
  n90 --> n79
  n91 --> n79
  n92 --> n93
  n92 --> n94
  n92 --> n95
  n92 --> n79
  n93 --> n92
  n94 --> n95
  n94 --> n79
  n95 --> n96
  n95 -.-> n97
  n95 -.-> n97
  n96 --> n79
  n98 --> n99
  n98 --> n104
  n98 --> n78
  n98 --> n100
  n99 --> n110
  n99 --> n98
  n100 --> n101
  n100 -.-> n103
  n100 -.-> n103
  n101 --> n98
  n102 --> n110
  n102 --> n98
  n104 --> n98
  n105 --> n106
  n105 --> n59
  n105 --> n107
  n105 --> n109
  n106 --> n59
  n107 --> n108
  n107 --> n110
  n107 --> n59
  n108 --> n107
  n110 --> n111
  n110 --> n119
  n111 --> n113
  n111 --> n112
  n112 --> n119
  n113 --> n114
  n113 --> n115
  n114 --> n119
  n114 --> n124
  n115 --> n116
  n115 --> n117
  n115 --> n118
  n116 --> n119
  n117 --> n119
  n118 --> n119
  n119 --> n120
  n119 --> n130
  n119 --> n133
  n119 --> n79
  n119 --> n107
  n119 --> n136
  n120 --> n121
  n120 --> n122
  n120 --> n123
  n120 --> n119
  n120 --> n125
  n120 --> n126
  n120 --> n115
  n121 --> n120
  n122 --> n120
  n123 --> n120
  n123 --> n124
  n124 --> n119
  n125 --> n120
  n126 --> n120
  n127 --> n119
  n128 --> n119
  n129 --> n119
  n130 --> n130
  n130 --> n132
  n130 --> n119
  n130 --> n131
  n131 --> n119
  n131 --> n115
  n132 --> n119
  n133 --> n133
  n133 --> n119
  n134 --> n119
  n135 --> n137
  n135 --> n136
  n135 --> n1
  n136 --> n135
  n136 --> n119
  n137 --> n139
  n137 --> n138
  n137 --> n145
  n137 --> n135
  n138 --> n137
  n139 --> n140
  n139 -.-> n145
  n139 -.-> n145
  n140 --> n141
  n141 --> n142
  n141 -.-> n145
  n141 -.-> n145
  n142 --> n143
  n143 --> n144
  n143 -.-> n145
  n143 -.-> n145
  n144 --> n147
  n146 -.-> n147
  n147 --> n149
  n147 --> n148
  n147 --> n139
  n148 --> n147
  n149 --> n151
  n149 --> n150
  n149 --> n147
  n150 --> n153
  n150 --> n149
  n151 --> n152
  n151 --> n153
  n151 --> n149
  n151 --> n164
  n152 --> n153
  n152 --> n151
  n153 --> n154
  n153 --> n151
  n153 --> n150
  n153 --> n156
  n154 --> n155
  n154 -.-> n165
  n154 -.-> n165
  n155 --> n156
  n155 --> n153
  n156 --> n158
  n156 --> n153
  n156 --> n157
  n157 --> n156
  n158 --> n159
  n158 --> n160
  n158 --> n153
  n159 --> n160
  n160 --> n161
  n160 -.-> n165
  n160 -.-> n165
  n161 --> n153
  n162 --> n163
  n162 -.-> n165
  n162 -.-> n165
  n163 --> n151
  n164 --> n151
  classDef ext fill:#555,color:#ccc;
