flowchart LR
  n0["张江-落地坡道"]
  n1["张江-人工智能岛闸机外"]
  n2["张江-AI岛-水景"]
  n3["张江-华科路"]
  n4["张江-华科路-配送车"]
  n5["张江-街角"]
  n6["张江-街角-电车"]
  n7["张江-科苑路"]
  n8["张江-加油站"]
  n9["张江-加油站-便利店"]
  n10["张江-加油站-棚子"]
  n11["张江-加油站-棚子-战斗"]
  n12["张江-加油站-棚子-战斗-受伤"]
  n13["张江-加油站-棚子-胜利"]
  n14["张江-加油站-拎桶"]
  n15["结局-张江-加油站"]
  n16["张江-AI岛-园区内"]
  n17["张江-AI岛-公司前台"]
  n18["张江-AI岛-机房"]
  n19["张江-AI岛-机房-重逢"]
  n20["张江-AI岛-机房-长谈给卡"]
  n21["张江-AI岛-机房-话题"]
  n22["张江-AI岛-机房-话题-近况"]
  n23["张江-AI岛-机房-话题-华大规矩"]
  n24["张江-AI岛-机房-话题-北岸"]
  n25["张江-AI岛-机房-话题-洪金宝"]
  n26["张江-AI岛-机房-监控"]
  n27["张江-AI岛-机房-曹睿泽"]
  n28["张江-AI岛-机房-读报告"]
  n29["张江-AI岛-机房-休息"]
  n30["张江-AI岛-食堂"]
  n31["张江-AI岛-停车场"]
  n32["张江-上科大-校门"]
  n33["张江-上科大-研究生公寓"]
  n34["张江-上科大-公寓走廊"]
  n35["张江-上科大-走廊-别的门"]
  n36["张江-上科大-曹睿泽宿舍"]
  n37["张江-上科大-宿舍-合照"]
  n38["张江-上科大-宿舍-搜刮"]
  n39["张江-上科大-教学楼门厅"]
  n40["张江-上科大-食堂"]
  n41["张江-上科大-食堂-后厨"]
  n42["张江-上科大-食堂-后厨-战斗"]
  n43["张江-上科大-食堂-后厨-战斗-受伤"]
  n44["张江-上科大-食堂-后厨-胜利"]
  n45["结局-张江-上科大食堂"]
  n46["张江-华大-大门"]
  n47["张江-华大-大门-吃闭门羹"]
  n48["张江-华大-厂区广场"]
  n49["张江-华大-广场-人影"]
  n50["张江-华大-广场-近路"]
  n51["张江-华大-广场-近路-受伤"]
  n52["张江-华大-广场-近路-胜"]
  n53["结局-张江-厂区广场"]
  n54["张江-华大-保安亭"]
  n55["张江-华大-连廊"]
  n56["张江-华大-连廊-规程"]
  n57["张江-华大-连廊-遭遇"]
  n58["张江-华大-连廊-遭遇-受伤"]
  n59["张江-华大-连廊-遭遇-胜"]
  n60["结局-张江-连廊"]
  n61["张江-华大-办公区"]
  n62["张江-华大-办公区-工位"]
  n63["张江-华大-灰区"]
  n64["张江-华大-灰区-更衣柜"]
  n65["张江-华大-灰区-穿无尘服"]
  n66["张江-华大-灰区-脱无尘服"]
  n67["张江-华大-灰区-风淋复位"]
  n68["张江-华大-风淋舱"]
  n69["张江-华大-风淋舱-关门"]
  n70["张江-华大-风淋舱-开门"]
  n71["张江-华大-风淋舱-强启失败"]
  n72["张江-华大-风淋舱-吹风"]
  n73["张江-华大-风淋舱-倒计时"]
  n74["张江-华大-风淋舱-完成"]
  n75["张江-华大-风淋舱-击退"]
  n76["张江-华大-风淋舱-泄漏"]
  n77["张江-华大-风淋舱-泄漏-乱拍"]
  n78["张江-华大-风淋舱-泄漏-复位"]
  n79["张江-华大-风淋舱-泄漏-喊"]
  n80["张江-华大-风淋舱-泄漏-解除"]
  n81["结局-张江-风淋舱"]
  n82["张江-华大-洁净主走廊"]
  n83["张江-华大-白区"]
  n84["张江-华大-白区-围攻"]
  n85["张江-华大-白区-围攻-受伤"]
  n86["张江-华大-白区-围攻-胜"]
  n87["结局-张江-白区"]
  n88["张江-华大-白区-工位A"]
  n89["张江-华大-白区-工位A-观察"]
  n90["张江-华大-白区-工位A-试探"]
  n91["张江-华大-白区-工位战A"]
  n92["张江-华大-白区-工位战A-受伤"]
  n93["张江-华大-白区-工位战A-胜"]
  n94["张江-华大-白区-工位B"]
  n95["张江-华大-白区-工位B-观察"]
  n96["张江-华大-白区-工位B-对话"]
  n97["张江-华大-白区-工位B-误杀"]
  n98["张江-华大-白区-工位C"]
  n99["张江-华大-白区-工位C-观察"]
  n100["张江-华大-白区-工位C-试探"]
  n101["张江-华大-白区-工位战C"]
  n102["张江-华大-白区-工位战C-受伤"]
  n103["张江-华大-白区-工位战C-胜"]
  n104["结局-张江-毒气"]
  n105["张江-华大-运维区"]
  n106["张江-华大-运维区-虚惊"]
  n107["张江-华大-运维区-遭遇战"]
  n108["张江-华大-运维区-遭遇战-受伤"]
  n109["张江-华大-运维区-制服"]
  n110["张江-华大-运维区-闲聊"]
  n111["结局-张江-运维区"]
  n112["张江-华大-设备密室"]
  n113["张江-华大-夹层-入口"]
  n114["张江-华大-夹层-摸黑"]
  n115["张江-华大-夹层"]
  n116["张江-华大-夹层-俯瞰"]
  n117["结局-张江-夹层"]
  n118["张江-华大-动力站-初遇"]
  n119["张江-华大-动力站-会面"]
  n120["张江-华大-动力站-含糊"]
  n121["张江-华大-动力站-来历"]
  n122["张江-华大-动力站-委托"]
  n123["张江-华大-动力站-拷问"]
  n124["张江-华大-动力站-告知"]
  n125["张江-华大-动力站-谎言"]
  n126["张江-华大-动力站-沉默"]
  n127["张江-华大-动力站"]
  n128["张江-华大-动力站-聊天"]
  n129["张江-华大-动力站-聊天-自己"]
  n130["张江-华大-动力站-聊天-厂里"]
  n131["张江-华大-动力站-曹睿泽-委托"]
  n132["张江-华大-动力站-曹睿泽-回报"]
  n133["张江-华大-动力站-合照"]
  n134["张江-华大-动力站-报告"]
  n135["张江-华大-动力站-补救"]
  n136["张江-华大-动力站-柴油-接"]
  n137["张江-华大-动力站-柴油-交"]
  n138["张江-华大-动力站-纯水"]
  n139["张江-华大-动力站-灌水"]
  n140["张江-华大-动力站-取样瓶"]
  n141["张江-华大-动力站-休息"]
  n142["张江-华大-动力站-字条"]
  n143["张江-滨河绿道"]
  n144["张江-厂界便道"]
  n145["张江-川杨河南岸堤"]
  n146["张江-川杨河南岸堤-探引桥"]
  n147["张江-川杨河大桥-1"]
  n148["张江-川杨河大桥-1-受伤"]
  n149["张江-川杨河大桥-1-胜"]
  n150["张江-川杨河大桥-2"]
  n151["张江-川杨河大桥-2-受伤"]
  n152["张江-川杨河大桥-2-胜"]
  n153["张江-川杨河大桥-3"]
  n154["张江-川杨河大桥-3-受伤"]
  n155["张江-川杨河大桥-3-胜"]
  n156["结局-张江-川杨河"]
  n157["张江-北岸落地"]
  n158["张江-河北岸-街口"]
  n159["张江-河北岸-沿街铺面"]
  n160["张江-检测中心-大门"]
  n161["张江-检测中心-卸货区"]
  n162["张江-检测中心-大厅"]
  n163["张江-检测中心-台账"]
  n164["张江-检测中心-走廊"]
  n165["张江-检测中心-瞎摸"]
  n166["张江-检测中心-瞎摸-受伤"]
  n167["张江-检测中心-瞎摸-胜"]
  n168["张江-检测中心-三室外"]
  n169["张江-检测中心-三室外-窥视"]
  n170["张江-检测中心-三室内"]
  n171["张江-检测中心-摔柜门"]
  n172["张江-检测中心-检测员战"]
  n173["张江-检测中心-检测员战-受伤"]
  n174["张江-检测中心-制服"]
  n175["张江-检测中心-撤离遭遇"]
  n176["张江-检测中心-撤离遭遇-受伤"]
  n177["张江-检测中心-撤离-胜"]
  n178["张江-检测中心-抄录"]
  n179["结局-张江-检测中心"]
  n180["↔北蔡镇罗山立交桥"]:::ext
  n181["↔整理整理"]:::ext
  n182["↔张江立交桥"]:::ext
  n0 -.-> n1
  n1 --> n16
  n1 --> n3
  n1 --> n5
  n1 --> n143
  n1 --> n2
  n2 --> n1
  n3 --> n4
  n3 --> n46
  n3 --> n1
  n4 --> n3
  n5 --> n6
  n5 --> n8
  n5 --> n7
  n5 --> n1
  n6 --> n5
  n7 --> n32
  n7 --> n5
  n8 --> n9
  n8 --> n10
  n8 --> n5
  n9 --> n8
  n10 --> n11
  n10 --> n8
  n10 --> n14
  n11 --> n13
  n11 -.-> n15
  n12 --> n10
  n13 --> n10
  n14 --> n8
  n16 --> n17
  n16 --> n30
  n16 --> n31
  n16 --> n1
  n17 --> n18
  n17 --> n16
  n18 --> n19
  n18 --> n21
  n18 --> n26
  n18 --> n29
  n18 --> n17
  n19 --> n20
  n20 --> n18
  n21 --> n22
  n21 --> n23
  n21 --> n24
  n21 --> n25
  n21 --> n18
  n22 --> n21
  n23 --> n21
  n24 --> n21
  n25 --> n21
  n26 --> n18
  n27 --> n18
  n28 --> n18
  n29 --> n29
  n29 --> n18
  n30 --> n16
  n31 --> n16
  n32 --> n33
  n32 --> n39
  n32 --> n7
  n33 --> n34
  n33 --> n40
  n33 --> n32
  n34 --> n36
  n34 --> n35
  n34 --> n33
  n35 --> n34
  n35 --> n33
  n36 --> n37
  n36 --> n38
  n36 --> n34
  n37 --> n36
  n38 --> n36
  n39 --> n32
  n40 --> n41
  n40 --> n33
  n41 --> n42
  n41 --> n40
  n41 --> n41
  n42 --> n44
  n42 -.-> n45
  n43 --> n41
  n44 --> n41
  n46 --> n48
  n46 --> n47
  n46 --> n3
  n47 --> n46
  n48 --> n49
  n48 --> n54
  n48 --> n46
  n48 --> n50
  n49 --> n48
  n50 --> n52
  n50 -.-> n53
  n51 --> n54
  n51 --> n48
  n52 --> n54
  n52 --> n48
  n54 --> n55
  n54 --> n48
  n55 --> n56
  n55 --> n63
  n55 --> n61
  n55 --> n54
  n55 --> n57
  n56 --> n55
  n57 --> n59
  n57 -.-> n60
  n58 --> n55
  n59 --> n55
  n61 --> n62
  n61 --> n55
  n62 --> n61
  n63 --> n68
  n63 --> n64
  n63 --> n113
  n63 --> n55
  n63 --> n67
  n64 --> n65
  n64 --> n66
  n64 --> n63
  n65 --> n63
  n66 --> n63
  n67 --> n63
  n68 --> n69
  n68 --> n71
  n68 --> n63
  n68 --> n74
  n69 --> n68
  n70 --> n68
  n71 --> n68
  n72 --> n73
  n72 --> n75
  n72 --> n76
  n73 --> n74
  n74 --> n82
  n75 --> n63
  n75 -.-> n81
  n76 --> n77
  n76 --> n79
  n76 --> n78
  n77 --> n76
  n77 --> n80
  n78 --> n80
  n79 --> n76
  n80 --> n63
  n82 --> n83
  n82 --> n105
  n82 --> n68
  n83 --> n84
  n83 --> n82
  n83 --> n88
  n83 --> n94
  n83 --> n98
  n83 --> n127
  n84 --> n86
  n84 -.-> n87
  n85 --> n82
  n86 --> n82
  n88 --> n89
  n88 --> n90
  n88 --> n91
  n88 --> n83
  n89 --> n88
  n90 --> n91
  n90 --> n83
  n91 --> n93
  n91 -.-> n87
  n92 --> n83
  n93 --> n83
  n94 --> n95
  n94 --> n96
  n94 --> n97
  n94 --> n83
  n95 --> n94
  n96 --> n83
  n97 --> n83
  n98 --> n99
  n98 --> n100
  n98 --> n101
  n98 --> n83
  n99 --> n98
  n100 --> n101
  n100 --> n83
  n101 --> n103
  n101 -.-> n104
  n102 --> n83
  n103 --> n83
  n105 --> n106
  n105 --> n112
  n105 --> n82
  n105 --> n107
  n106 --> n118
  n106 --> n105
  n107 --> n109
  n107 -.-> n111
  n108 --> n105
  n109 --> n105
  n110 --> n118
  n110 --> n105
  n112 --> n105
  n113 --> n114
  n113 --> n63
  n113 --> n115
  n113 --> n117
  n114 --> n63
  n115 --> n116
  n115 --> n118
  n115 --> n63
  n116 --> n115
  n118 --> n119
  n118 --> n127
  n119 --> n121
  n119 --> n120
  n120 --> n127
  n121 --> n122
  n121 --> n123
  n122 --> n127
  n122 --> n132
  n123 --> n124
  n123 --> n125
  n123 --> n126
  n124 --> n127
  n125 --> n127
  n126 --> n127
  n127 --> n128
  n127 --> n138
  n127 --> n141
  n127 --> n83
  n127 --> n115
  n127 --> n144
  n128 --> n129
  n128 --> n130
  n128 --> n131
  n128 --> n127
  n128 --> n133
  n128 --> n134
  n128 --> n123
  n129 --> n128
  n130 --> n128
  n131 --> n128
  n131 --> n132
  n132 --> n127
  n133 --> n128
  n134 --> n128
  n135 --> n127
  n136 --> n127
  n137 --> n127
  n138 --> n138
  n138 --> n140
  n138 --> n127
  n138 --> n139
  n139 --> n127
  n139 --> n123
  n140 --> n127
  n141 --> n141
  n141 --> n127
  n142 --> n127
  n143 --> n145
  n143 --> n144
  n143 --> n1
  n144 --> n143
  n144 --> n127
  n145 --> n147
  n145 --> n146
  n145 --> n156
  n145 --> n143
  n146 --> n145
  n147 --> n149
  n147 -.-> n156
  n148 --> n150
  n149 --> n150
  n150 --> n152
  n150 -.-> n156
  n151 --> n153
  n152 --> n153
  n153 --> n155
  n153 -.-> n156
  n154 --> n158
  n155 --> n158
  n157 -.-> n158
  n158 --> n160
  n158 --> n159
  n158 --> n147
  n159 --> n158
  n160 --> n162
  n160 --> n161
  n160 --> n158
  n161 --> n164
  n161 --> n160
  n162 --> n163
  n162 --> n164
  n162 --> n160
  n162 --> n178
  n163 --> n164
  n163 --> n162
  n164 --> n165
  n164 --> n162
  n164 --> n161
  n164 --> n168
  n165 --> n167
  n165 -.-> n179
  n166 --> n168
  n166 --> n164
  n167 --> n168
  n167 --> n164
  n168 --> n170
  n168 --> n164
  n168 --> n169
  n169 --> n168
  n170 --> n171
  n170 --> n172
  n170 --> n164
  n171 --> n172
  n172 --> n174
  n172 -.-> n179
  n173 --> n164
  n174 --> n164
  n175 --> n177
  n175 -.-> n179
  n176 --> n162
  n177 --> n162
  n178 --> n162
  classDef ext fill:#555,color:#ccc;
