flowchart LR
  n0["日记本"]
  n1["日记本-写"]
  n2["日记本-写-空白"]
  n3["日记本-写好了"]
  n4["整理整理-丢日记本"]
  n5["↔整理整理"]:::ext
  n0 --> n0
  n0 --> n1
  n1 --> n3
  n1 -.-> n2
  n1 --> n0
  n2 --> n0
  n3 --> n1
  n3 --> n0
  classDef ext fill:#555,color:#ccc;
